### ISSUE TITLE
Concurrent backup and restore

### ISSUE THREAD

**Issue by TimothyTitan** [github/backup-utils#1017]
Is it possible to allow a concurrent backup and restore at the same time?

I want to restore daily to a secondary server without interrupting our prod backup schedule. We have a rather large instance - It takes ~3 hours to backup and ~4 hours to restore and I'm hoping that there is a way to accommodate the restore without pausing backups for that duration.

**Comment by Lubot17** [comment]
Tim Titan i remember i have investment to this platform, isn't?

Maricel Cleobit

Noong Biy, Mar 3, 2023, 16:24, isinulat ni Tim Titan <
***@***.***> ang:

**Comment by BangRegar2001** [comment]
Bisa kah Saya Menghapus kode vertivikasi 
Soal nya saya Tidak dapat Info lagi no tidak aktif Pasword lupa

**Comment by davidjarzebowski** [comment]
@TimothyTitan : It is not currently possible to run a backup and a restore at the same time.

Also, as described in [this issue](https://github.com/github/backup-utils/issues/1140), we are making changes to the backup-utils repository today.

I have moved this issue into our internal repository so we can consider working on this issue in the future.
