### ISSUE TITLE
How to answer: "Where did all my inodes go?"

### ISSUE THREAD

**Issue by solvaholic** [github/backup-utils#1020]
👋 Hiyo! I'd like to find a repeatable way to answer "Where did all my inodes go?", in the context of a **backup-utils** data volume.

If I [use the Docker image](https://github.com/github/backup-utils/blob/master/docs/docker.md) to run `ghe-backup`, then I can also use it to examine the data volume. For example:

```shell
docker run -it --rm -v "ghe-backup-data:/data:ro" github/backup-utils /bin/bash
```

From within that context, I'd like to answer:

- [x] How many inodes are consumed by all my backup snapshots?
- [x] How many new inodes does my `current` snapshot consume, relative to my previous snapshot?
- [x] Which portions of one snapshot consume inodes, relative to another snapshot?

I've been using `ls -i` to answer those questions, and I feel like there's probably a more robust or elegant way. I'll share what I'm doing in comments. Please let me know if you prefer alternatives, or have feedback :bow:

**Comment by djdefi** [comment]
`df -i` is another way to see `inode` utilization on a volume level. If a dedicated backup data volume is utilize that might help with the 1st one.

**Comment by solvaholic** [comment]
>  How many inodes are consumed by all my backup snapshots?

```shell
ls -iR /data/* | grep -v ":$" | sort -u | wc -l
```

> How many new inodes does my current snapshot consume, relative to my previous snapshot?

```shell
_curr=/data/current
_prev=/data/20230313T193317
comm -13 <( ls -iR $_prev | sort -u ) <( ls -iR $_curr | sort -u ) | grep -v ":$" | wc -l
```

> Which portions of one snapshot consume inodes, relative to another snapshot?

```shell
_curr=/data/20230313T193317
_prev=/data/20230313T191155
printf "inodes used in %s, and not in %s:\n" "$_curr" "$_prev"
for _dir in audit-log elasticsearch git-hooks pages repositories storage; do
  _count=$(comm -13 <( ls -iR $_prev/$_dir | sort -u ) <( ls -iR $_curr/$_dir | sort -u ) | grep -v ":$" | wc -l)
  printf "%s:\t%d\n" "$_dir" "$_count"
done
```

**Comment by solvaholic** [comment]
> `df -i` is another way to see `inode` utilization on a volume level. If a dedicated backup data volume is utilize that might help with the 1st one.

Thank you for reminding me `df -i` should help, @djdefi :bow:

I think this bit is key:

> dedicated backup data volume

When **/data** is a partition on a direct attached SSD, for example, I think `df -i` should provide meaningful output.

In other cases, **/data** may exist on a shared filesystem with other things the **backup-utils** admin can't see.

On my test setup, for example, I am NOT using a dedicated backup volume:

```text
root@a3e4f930f25e:~# df -i /data
Filesystem      Inodes   IUsed   IFree IUse% Mounted on
/dev/vda1      3907584 1177640 2729944   31% /data

root@a3e4f930f25e:~# ls -iR /data/* | grep -v ":$" | sort -u | wc -l
1611
```

**Comment by shcorbett** [comment]
@solvaholic did you get your question answered for this? If so, I can close this out otherwise can you open a separate issue in our internal ghes repo so we can take a look or we can discuss during our next triage call on best way to handle.

**Comment by solvaholic** [comment]
Thank you for following up on this @shcorbett :bow: I'm ok with closing this out and calling the answers in https://github.com/github/backup-utils/issues/1020#issuecomment-1468444825 sufficient.
