### ISSUE TITLE
ghe-export-mssql is not available

### ISSUE THREAD

**Issue by maennlse** [github/backup-utils#1054]
Hi, 
since updating our test env to v3.9.0 we see the following ERROR in the output of `ghe-backup`:
```text
2023-07-03T10:00:29Z  ERROR  ghe-export-mssql is not available
```
and mssql database dosn't seem to be back-upped (no mssql directory in th backup folder)...

after some checking, this seems to come from the `ghe_ssh_mssql` function in ghe-backup-mssql
```text
...
+ ghe_ssh_mssql 'test -e /usr/local/bin/ghe-export-mssql'
+ ghe-ssh '' '' <hostname> 'test -e /usr/local/bin/ghe-export-mssql'
+ log_error 'ghe-export-mssql is not available'
+ log_level error 'ghe-export-mssql is not available'
...
```

manually reverting [commit](https://github.com/github/backup-utils/commit/d4d4e313485cb2331deaffcee88fe4edf8f154d2) seems to 'fix' the issue for us...

actually i'm not sure if its some miss-configuration on our end, or if the above mentioned commit broke the mssql backup...

let me know if you need any more information.

thanks.

**Comment by shcorbett** [comment]
@boxofyellow can you take a look at this one -- looks like you may have owned that last commit referenced above

**Comment by boxofyellow** [comment]
@maennlse I was looking into this today was having a little trouble replicating the problem you described.  Would you be able to temporarily undo the revert and run `ghe-backup` with `-v` flag and share the results?  And just to double check which version of ghes are your targeting?

**Comment by michaelpsomiadis** [comment]
Hi, we've also been running into this, backup-utils v3.9.0 targeting a single instance of GitHub enterprise v3.9.0. Server that backup-utils is running on is CentOS 7.

```
$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
```

this is the relevant part of the output.
```
2023-07-12T00:09:58Z  INFO  Backing up MSSQL databases ...
Usage: ghe-ssh [<option>...] <host> [<simple-command>...]
       echo 'set -o pipefail; <complex-command>...' | ghe-ssh [<option>...] <host> /bin/bash
Helper to ssh into a GitHub instance with the right user and port. The first
form should be used for simple commands; the second form should be used for
complex commands that include pipelines or multiple commands.
2023-07-12T00:09:59Z  ERROR  ghe-export-mssql is not available
2023-07-12T00:09:59Z  INFO  Backing up Actions data ...
```
I added `set -x` to the `share/github-backup-utils/ghe-backup-mssql` script and this might help also.

```
+ backup_dir=/backup/ghent.local/20230712T103301/mssql
+ last_mssql=
+ backup_command=
+ backup_type=
+ full_expire=
+ diff_expire=
+ tran_expire=
+ trap cleanup EXIT INT
++ ghe-ssh ghent.local -- 'ghe-config cluster.mssql-master'
++ true
+ GHE_MSSQL_PRIMARY_NODE=
++ ghe-ssh ghent.local -- 'ghe-config cluster..hostname'
++ true
+ GHE_MSSQL_PRIMARY_HOST=
+ '[' -z '' ']'
+ GHE_MSSQL_PRIMARY_HOST=ghent.local
++ mktemp -d -t backup-utils-backup-XXXXXX
+ tempdir=/tmp/backup-utils-backup-84yvAE
+ ssh_config_file_opt=
+ opts=
++ ghe-ssh ghent.local -- 'ghe-config cluster.ha'
++ true
+ isHA=
+ '[' rsync = cluster ']'
+ '[' '' = true ']'
+ export_tool_available
+ '[' -z '' ']'
+ ghe_ssh_mssql 'test -e /usr/local/bin/ghe-export-mssql'
+ ghe-ssh '' '' ghent.local 'test -e /usr/local/bin/ghe-export-mssql'
Usage: ghe-ssh [<option>...] <host> [<simple-command>...]
       echo 'set -o pipefail; <complex-command>...' | ghe-ssh [<option>...] <host> /bin/bash
Helper to ssh into a GitHub instance with the right user and port. The first
form should be used for simple commands; the second form should be used for
complex commands that include pipelines or multiple commands.
+ log_error 'ghe-export-mssql is not available'
+ log_level error 'ghe-export-mssql is not available'
+ local level=error
+ shift
+ local 'message=ghe-export-mssql is not available'
```

**Comment by maennlse** [comment]
@boxofyellow thanks for looking into this.

we have the same setup as @michaelpsomiadis.

* backup host: CentOS 7
* using backup-utils 3.9.0
* standalone ghe instance v3.9.0


if i understand the code correctly... its (currently) working only for cluster setups, as the `$opts` and `ssh_config_file_opt` vars are set... 
on standalone setups these vars are empty... and `ghe-ssh` is failing/not working then.

the following patch/proposal might fix it...
(setting `opts` to have no password authentication, which is imho fine, and extending the `opts` var/array with the required opts for a cluster setup) 

```diff
--- ghe-backup-mssql    2023-07-12 10:12:43.166638060 +0200
+++ ghe-backup-mssql.new        2023-07-12 10:16:48.244559610 +0200
@@ -30,7 +30,7 @@ export_tool_available() {
 }
 
 ghe_ssh_mssql() {
-  ghe-ssh "${opts[@]}" "${ssh_config_file_opt[@]}" "$GHE_MSSQL_PRIMARY_HOST" "$@"
+  ghe-ssh "${opts[@]}" "$GHE_MSSQL_PRIMARY_HOST" "$@"
 }
 
 cleanup() {
@@ -47,16 +47,15 @@ if [ -z "$GHE_MSSQL_PRIMARY_HOST" ]; the
 fi
 
 tempdir=$(mktemp -d -t backup-utils-backup-XXXXXX)
-ssh_config_file_opt=
-opts=
+opts=("-o" "PasswordAuthentication=no")
 
 isHA="$(ghe-ssh "$GHE_HOSTNAME" -- "ghe-config cluster.ha" || true)"
 
 # get server hostnames under cluster and HA
 if [ "$GHE_BACKUP_STRATEGY" = "cluster" ] || [ "$isHA" = "true" ]  ; then
   ssh_config_file="$tempdir/ssh_config"
-  ssh_config_file_opt=("-F" "$ssh_config_file")
-  opts=("-o" "UserKnownHostsFile=/dev/null" "-o" "StrictHostKeyChecking=no" "-o" "PasswordAuthentication=no")
+  opts+=("-o" "UserKnownHostsFile=/dev/null" "-o" "StrictHostKeyChecking=no")
+  opts+=("-F" "$ssh_config_file")
   ghe-ssh-config "$GHE_HOSTNAME" "$GHE_MSSQL_PRIMARY_HOST" > "$ssh_config_file"
 fi
```

**Comment by boxofyellow** [comment]
I have a repro now, I was using cluster instances that I was using for other testing.  Upon spinning up a new single node instance the problem repro'ed right a way.

**Comment by boxofyellow** [comment]
I'm sorry our automation closed this as the fix landed in the main branch.  I'll reopen it to make it clearer when the backports have landed.

**Comment by uberjay** [comment]
Where _is_ the fix for this? I've also run into this and fixed it myself. (along with adding `bc` to the runtime docker container, as it seems to have been missed -- will file an issue for this momentarily.)

**Comment by michaelfdickey** [comment]
thanks @boxofyellow !

would this be fixed just by having them modify those two lines in `ghe-backup-mssql` on their ghes and then just running `ghe-config-apply` again?
does this look like it might have caused the actions-cache issue (no ldf file, container is critical) or is that separate?

**Comment by boxofyellow** [comment]
Small updated for when the fix will be released.  We did make the 3.9.1 patch deadline, and that should get released some time next week on https://github.com/github/backup-utils/releases.  I'll report back when that happens.

**Comment by boxofyellow** [comment]
Another small update the two releases (for 3.8 and 3.9) have been created, they are still draft, but I would expect them be finalized soon
- 3.9: https://github.com/github/backup-utils/releases/tag/untagged-8c4c9588f60d408a6103
- 3.8: https://github.com/github/backup-utils/releases/tag/untagged-83a6638b77a3f44ffe1d

**Comment by boxofyellow** [comment]
Sorry for the delay but the fix has been released
- 3.9: https://github.com/github/backup-utils/releases/tag/v3.9.1
- 3.8: https://github.com/github/backup-utils/releases/tag/v3.8.1

So I'm going to close this one out now.
