### ISSUE TITLE
stable branch pointing on 3.8

### ISSUE THREAD

**Issue by lorenzo-psa** [github/backup-utils#1060]
Hello,

Could you set up the stable branch to the latest version in accordance to the [documentation](https://github.com/github/backup-utils/blob/master/docs/getting-started.md) ?

**Comment by ThatStoney** [comment]
Hi,

Thank you for opening this issue. I've opened an internal issue with the Backup Utilities engineering team to get this fixed. I'll update once complete.

**Comment by ThatStoney** [comment]
Hi @lorenzo-psa,

I have confirmed this issue is resolved. Thank you for reporting it to us.
