### ISSUE TITLE
Please add flag to disable disk space preflight checks

### ISSUE THREAD

**Issue by ncstate-mafields** [github/backup-utils#1080]
The recent changes in v3.9.0 adds an unskippable step before the backup is taken to determine the disk space that will be used by the backup process, and compares the local disk space to ensure there is enough space and aborts if there is not. 

However, it takes almost as long to calculate this value as it does to actually take the backup, resulting in almost doubling the total duration of the backup process. Our daily backup went from just under an hour total runtime on average to just under two hours, with 45 minutes of that time waiting on the disk space estimate to come back. 

While I can appreciate the extra precaution, the performance hit is not a worth-while trade-off in our environment. 

Please add a flag that can be passed to the backup script to skip this check.

**Comment by younsl** [comment]
IMO, I hope to support the `-f` force option in the `ghe-backup` command.

https://github.com/github/backup-utils/blob/01fef2b2ca018b43afd6c21eb269a026bb8391a1/bin/ghe-backup#L1-L11

**Comment by chuckp22** [comment]
Flag to disable check added in the next upcoming patch.
