### ISSUE TITLE
ghe-rsync-feature-checker assumes GNU grep

### ISSUE THREAD

**Issue by memphis88** [github/backup-utils#1087]
While upgrading to 3.9 I noticed `GHE_EXTRA_RSYNC_OPTS` did not work on my container. After some digging I ended up on the problem being the regex not working the same between GNU grep & BSD (which is what busybox, the base of alpine, seem to come with out of the box). Installing grep from the alpine registry fixes the issue but I think it's best to not make assumptions on which grep is present on the machine. This applies to any argument with the double dashes, another workaround is to not use any dashes.

Change in question:
https://github.com/github/backup-utils/commit/f5071c749d174e5a7251767692ea3a30c793a2ad#diff-ee1b8c66511ad26f989da164d9f2fbf365aa63803cfa88989fd6d67fc0804febR19

Here's how it behaves between when run with BSD grep (the regex engine returns `found_command=-trust-sender`)
```bash
➜  backup-utils git:(master) ✗ ./share/github-backup-utils/ghe-rsync-feature-checker --trust-sender
+ rsync_command=--trust-sender
++ echo --trust-sender
++ grep -oE '^-+'
+ leading_dashes=--
++ echo --trust-sender
++ sed -E 's/^-+//'
+ normalized_command=trust-sender
++ rsync -h
++ grep -oE '\B-+(trust-sender)\b'
++ head -n 1
+ found_command=-trust-sender
++ echo -trust-sender
++ sed -E 's/^-+//'
+ normalized_found_command=trust-sender
+ '[' -- == - ']'
+ '[' -- == -- ']'
+ '[' --trust-sender == -trust-sender ']'
+ echo false
false
```
And with GNU
```bash
➜  backup-utils git:(master) ✗ ./share/github-backup-utils/ghe-rsync-feature-checker --trust-sender
+ rsync_command=--trust-sender
++ echo --trust-sender
++ grep -oE '^-+'
+ leading_dashes=--
++ echo --trust-sender
++ sed -E 's/^-+//'
+ normalized_command=trust-sender
++ rsync -h
++ ggrep -oE '\B-+(trust-sender)\b'
++ head -n 1
+ found_command=--trust-sender
++ echo --trust-sender
++ sed -E 's/^-+//'
+ normalized_found_command=trust-sender
+ '[' -- == - ']'
+ '[' -- == -- ']'
+ '[' --trust-sender == --trust-sender ']'
+ echo true
true
```

**Comment by davidjarzebowski** [comment]
As described in [this issue](https://github.com/github/backup-utils/issues/1140), we are making changes to the backup-utils repository today.

I have moved this issue into our internal repository so we can consider working on this issue in the future.
