### ISSUE TITLE
unnecessary stderr output in ghe-host-check

### ISSUE THREAD

**Issue by maennlse** [github/backup-utils#1114]
`ghe-host-check` adds an (imho) unnecessary 'empty line' to stderr.

```diff
--- ghe-host-check.org  2023-08-31 14:44:35.180753911 +0200
+++ ghe-host-check      2023-08-31 14:44:51.737797321 +0200
@@ -256,5 +256,4 @@ SKIP_MSG
     echo " - jq ${jq_version} >= required ($min_jq)" 1>&2
   fi
 fi
-echo "" 1>&2
 echo "Connect $hostname:$port OK (v$version)"
```

which shouldn't be an error at all.

**Comment by davidjarzebowski** [comment]
As described in [this issue](https://github.com/github/backup-utils/issues/1140), we are making changes to the backup-utils repository today.

I have moved this issue into our internal repository so we can consider working on this issue in the future.
