### ISSUE TITLE
/etc/issue.net doesn't provide OS version

### ISSUE THREAD

**Issue by joeomc** [github/backup-utils#1117]
Hello, this line doesn't work as expected RHEL based systems.

https://github.com/github/backup-utils/blob/67009867fcfa6b5533c090847fd9365bd78b9336/bin/ghe-backup#L232

`/etc/issue.net`  on RHEL based systems doesn't provide OS version.  
From Centos 7, 8 and Rocky 9:
```
cat /etc/issue.net
\S
Kernel \r on an \m
```

man page issue.net(5) provides more details to what those sequences are.

**Comment by davidjarzebowski** [comment]
@joeomc : This will be fixed in backup-utils v3.11.0
