### ISSUE TITLE
Incremental backups docs - correct required variable

### ISSUE THREAD

**Issue by georgebrockman** [github/backup-utils#1133]
Hi, recently implemented incremental backups and was following the docs here https://github.com/github/backup-utils/blob/master/docs/incremental-mysql-backups-and-restores.md#configuring-number-of-backups, the variable suggested in the docs is `GHE_INCREMENTAL_BACKUP_MAX` rather than `GHE_INCREMENTAL_MAX_BACKUPS`, wondering if that could be updated in the docs for others to avoid that pitfall?

**Comment by gamefiend** [comment]
Thanks for spotting the typo! This updated and will be rolled out with the docs in the future.
