### ISSUE TITLE
Please read - Changes are coming to this repository

### ISSUE THREAD

**Issue by davidjarzebowski** [github/backup-utils#1140]
# This repository is changing

Today we are announcing a number of changes to the backup-utils repository. These changes will improve our (GitHub’s) ability to ship enhancements and new features to backup-utils, as well as simplify how GitHub Enterprise Server customers interact with backup-utils.

Our current process for shipping new versions of backup-utils involves a 2-way sync between this repository and an internal repository. This 2-way sync has become significantly more problematic now that we are regularly shipping patches in alignment with GitHub Enterprise Server. 

We will be stopping this 2-way sync so that our internal repository becomes the source of truth for the backup-utils source code. After the 2-way sync is stopped, this repository will be used to host documentation about backup-utils and to publish new versions of backup-utils. You will be able to access a specific version of backup-utils (which includes the full source code) from the [release page](https://github.com/github/backup-utils/releases) of this repository.

This change will not affect the functionality of the backup-utils tool or a customer’s ability to backup or restore their GitHub Enterprise Server instance. We ask customers to add any general questions they have about this change (e.g. about timing) to this issue.

## Details

There are three specific areas that will be affected when we stop the 2-way sync between our internal repository and this public repository:

1. **Pull requests**: Customers will no longer be able to open pull requests in the backup-utils repository. This is necessary because we will no longer be syncing changes between this repository and our internal repository.
2. **Issues**: Customers will no longer be able to open issues in the public backup-utils repository. Instead, customers will need to follow the standard support process and open a support ticket for any questions/concerns/problems with backup-utils. This will ensure all customer requests are handled consistently.
3. **Installing/upgrading backup-utils**: Customers will not be able to use a clone of the repository to install and upgrade backup-utils. Customers will need to download a specific version of backup-utils from the [release page](https://github.com/github/backup-utils/releases) (either as a Debian package or as an archive file - see below for details on how to incorporate this change).

## Timeline

We will be rolling these changes out in two phases:

* **Phase 1 (rolling out on 2023-11-30):** We will close all open pull requests and issues (after reviewing each one and porting them to our internal repository if merited), and update the repository settings so that new issues and pull requests cannot be created. Finally, we will stop syncing code from our internal repository to this repository.
    * You will still be able to get a working copy of backup-utils by cloning the repository after this date. But the code will not be updated in the repository; you can access updated versions of backup-utils via the [release page](https://github.com/github/backup-utils/releases).
* **Phase 2 (rolling out 2024-02-20):** The backup-utils code will be removed and the repository will be used to host documentation for backup-utils. After this date, you will no longer be able to clone a working copy of backup-utils from the repository. Instead, you will need to download a specific version of backup-utils from the [release page](https://github.com/github/backup-utils/releases).

### Clone of repository

If your current process for upgrading backup-utils involves a clone of the repository, you will need to modify your process to download a new version of backup-utils and set it up.

For example, you could download the v3.10.0 (github-backup-utils-v3.10.0.tar.gz) artifact from the [releases page](https://github.com/github/backup-utils/releases/tag/v3.10.0) with:

```
$ wget https://github.com/github/backup-utils/releases/download/v3.10.0/github-backup-utils-v3.10.0.tar.gz
```

And then extract it:

```
$ tar xzvf github-backup-utils-v3.10.0.tar.gz
```

This will give you a new folder, `github-backup-utils-v3.10.0`, which contains the code for version 3.10.0 of backup-utils. Once you copy over your backup.config file from a previous installation of backup-utils your new version of backup-utils will be ready to use.

### Docker

For customers that currently use Docker to create a backup-utils image, their existing process may need updating as a result of this change. Previously customers could execute this command to build a Docker image of backup-utils:

```
$ docker build github.com/github/backup-utils
```

This will not work after phase 2 roles out. You will need to update your process to first download an archive from the [release page](https://github.com/github/backup-utils/releases), extract it, and then build the Dockerfile inside the extracted directory.

**Comment by younsl** [comment]
**Question**: This topic is not directly related.
Is there a roadmap to support Kubernetes workloads like Helm Chart? There is no official Helm chart, so I developed and operated it myself. (#1067, #1016)

**Comment by davidjarzebowski** [comment]
> **Question**: This topic is not directly related. Is there a roadmap to support Kubernetes workloads like Helm Chart? There is no official Helm chart, so I developed and operated it myself. ([#1067](https://github.com/github/backup-utils/issues/1067), [#1016](https://github.com/github/backup-utils/issues/1016))

Thanks for your question @younsl . There are no plans right now to support Helm Chart.

**Comment by SolomonHD** [comment]
This affects our ansible workflow as we git pull -> checkout branch -> build dockerfile. Nothing is copied from GitHub unless the branch changes. I'm concerned about switching to a curl/wget setup as I don't want to download from GitHub every time we run a backup, which is frequently. 

I could add some caching logic, but I don't see an easy way to tell what's the version of an extracted folder. Could you add a version file somewhere that just contains the release version?

**Comment by MPCmcarpent** [comment]
If the main concern was managing a 2 way sync of the internal and external repositories. 

For phase two, instead of removing the code and replacing it with documentation. Is there any chance to convert this as only a 1-way mirror from your internal repository.  

Managing this with release archives and copying the config from folder to folder is going to add more complexity when bringing this into our air-gapped environment.

**Comment by davidjarzebowski** [comment]
> This affects our ansible workflow as we git pull -> checkout branch -> build dockerfile. Nothing is copied from GitHub unless the branch changes. I'm concerned about switching to a curl/wget setup as I don't want to download from GitHub every time we run a backup, which is frequently.
> 
> I could add some caching logic, but I don't see an easy way to tell what's the version of an extracted folder. Could you add a version file somewhere that just contains the release version?

@SolomonHD : The version of backup-utils is stored in this file: `share/github-backup-utils/version`.

**Comment by davidjarzebowski** [comment]
> If the main concern was managing a 2 way sync of the internal and external repositories.
> 
> For phase two, instead of removing the code and replacing it with documentation. Is there any chance to convert this as only a 1-way mirror from your internal repository.
> 
> Managing this with release archives and copying the config from folder to folder is going to add more complexity when bringing this into our environment.

Thanks for sharing your concern @MPCmcarpent . I appreciate this change does add complexity on your side.

Unfortunately, due to the way we develop and ship backup-utils a 1-way mirror as you described is not something we're able to do. I'm sorry I don't have a better solution for you.

**Comment by memphis88** [comment]
To add to the feedback about no longer providing source as a git repository, your decision makes reviewing the source code far more inconvenient. This comes as a surprise from a company that does version control at its core. Much like @MPCmcarpent, I would also recommend a 1-way sync at the very least if 2-way makes it unmaintainable.

**Comment by davidjarzebowski** [comment]
> To add to the feedback about no longer providing source as a git repository, your decision makes reviewing the source code far more inconvenient. This comes as a surprise from a company that does version control at its core. Much like [@MPCmcarpent](https://github.com/MPCmcarpent), I would also recommend a 1-way sync at the very least if 2-way makes it unmaintainable.

@memphis88 : Thanks for sharing your feedback. Unfortunately a 1-way sync was not a solution that we felt would work as well as the one we went with, especially given the way we handle multiple versions of backup-utils.

I'm going to close this issue now as part of this change, but please contact our [support team](https://support.github.com/) if you'd like to leave further feedback.
