### ISSUE TITLE
Backup utils stable points to 3.10

### ISSUE THREAD

**Issue by ymadavar** [github/backup-utils#1157]
Hi, Looks like backup utils latest version 3.10.2 release is not pointing to stable version, looks like stable is pointing to 3.10.0 backup utils version. Can we know when 3.10.2 can be pointed to stable version. Thanks.

**Comment by davidjarzebowski** [comment]
@ymadavar : Please read [this issue](https://github.com/github/backup-utils/issues/1140), which has details on how we are updating this repository.
