### ISSUE TITLE
backing up to an NFSv4 mount

### ISSUE THREAD

**Issue by em295** [github/backup-utils#118]
Does anyone get issues backing up using an NFS mount?

After running the `./bin/ghe-backup` command, I get lots of these rsync errors:
```
rsync: chown "/nfs/ghe-backup/data/20150220T171337/repositories/path/to/files" failed: Invalid argument (22)

rsync: chgrp "/nfs/ghe-backup/data/20150220T171337/elasticsearch/gh-enterprise-es/nodes/0/indices/code-search/0/index/._2t.nvm.qZHPmq" failed: Invalid argument (22)
```

which end in:
```
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1505) [generator=3.0.6]
Completed backup of GHESERVER:22 in snapshot 20150220T171337 at 17:20:12
Error: Snapshot incomplete. Some steps failed: repositories, pages, elasticsearch. 
```

rsync is trying to preserve the same file owner/group in the backup process.
So what usernames/groups/ids do I need to replicate from GHE to my LDAP?

Or, sorry in advance, am I being stupid and missing something obvious?

**Comment by lildude** [comment]
The error you are getting from rsync is indeed a username and group name resolution issue.  Your NFS server doesn't appear to know about the user you are performing the backup as.

Configuring your NFS server to use the same name service as your backup host (ie make them both use LDAP for authentication, users & groups) and ensuring your NFS share is not an anonymous share should resolve this issue.

If you can't make both hosts use the same name service, you need to ensure your NFS server can map the username and group of the user performing the backups to a valid userid and groupid.

**Comment by em295** [comment]
Yeah so in my case I was using nfsv4 so I would need to know the ids of the users on the GHE server itself, ie: git (500:500) and elasticsearch (108:116) and add them into LDAP, so the NFS server idmapper works. I can get that by ssh'ing into the GHE server and looking them up.

Using nfsv3 works for now as the UID/GID number is sufficient for it.

Just saying for rsyncing to nfsv4, that might wanna be in the requirements somewhere, though this issue is good enough to search on if one gets into the same situation I did.

**Comment by lildude** [comment]
Great!! Thanks for the useful information.
