### ISSUE TITLE
__gitmon__ directory not created during restore to 11.10.x

### ISSUE THREAD

**Issue by ometa** [github/backup-utils#119]
`backup_utils version 2.0.2`

The `/data/repositories/__gitmon__` directory is not being created after a restore to a 11.10 series appliance.  This has the effect of breaking the entire administration GUI **and** API.  From today's conversation with GHE support:

> ...noted that the __gitmon__ directory will not be automatically re-created yet, so you will still have to do that step manually, and I believe it will be necessary after each restore. (This issue only affects the 11.10 series; it's not needed for 2.0 or 2.1.)

The mitigation steps as provided by support are:
```bash
god stop gitmon 
yes | ghe-unlock 
sudo mkdir /data/repositories/__gitmon__ 
sudo chown -R git:git /data/repositories/__gitmon__ 
sudo enterprise-configure 
ghe-lock 
god start gitmon
```

We are being bitten by this issue across our various GHE appliances.  This is not a sustainable solution.  Can this please be highly prioritized since it's breaking restores?

Thanks!

**Comment by lildude** [comment]
I've just re-tested with the latest code in the master branch (now that https://github.com/github/backup-utils/pull/100 has been merged) to an 11.10.352 instance (you really should be running this release due to security issues in earlier releases) and I can confirm the `/data/repositories/__gitmon__` directory is now automatically recreated.

**Comment by lildude** [comment]
I've now tested with a clean 11.10.348 instance and the same thing applies there.  The `/data/repositories/__gitmon__` directory _is_ automatically recreated.

So with the latest code in backup-utils, there is no need to run any commands manually.

**Comment by ometa** [comment]
Awesome!  I will grab that and give it a whirl today.  Thanks for the prompt assistance.

**Comment by rtomayko** [comment]
I think this is safe to close. We could theoretically patch this up for earlier 11.10.3xx versions on the backup-utils side but I'm hoping that won't be necessary.
