### ISSUE TITLE
unlink will fail on Solaris unless backup is run as root

### ISSUE THREAD

**Issue by janorn** [github/backup-utils#123]
unlink is located in /usr/sbin on Solaris. Due to this unlink of in-progress will fail unless run as root.

Cron on Solaris does not allow PATH configuration. You can do it for all users in /etc/default/cron but that will affect all cron entries.

Default Cron path is /usr/bin for normal users and /usr/sbin:/usr/bin for root.

I would suggest to have a check if unlink is in /usr/bin or /usr/sbin and use this instead of a PATH dependency.

**Comment by janorn** [comment]
Solved by PR#294

**Comment by lildude** [comment]
As I've just commented in https://github.com/github/backup-utils/issues/185#issuecomment-287347451, if all you need to do is add `/usr/sbin` to the `PATH` in ghe-backup-config you can do so by adding `PATH=/usr/sbin:$PATH` to the end of your `backup.config` file within your backup-utils directory.

**Comment by 236084298** [comment]
https://github.com/github/backup-utils/issues/505#issuecomment-518072743

**Comment by 236084298** [comment]
https://github.com/github/backup-utils/issues/123#issuecomment-287347625

**Comment by shcorbett** [comment]
Looks like based on the above comments this may be resolved  - will wait a few days and then close this out (especially since this has been open since 2017!)
