### ISSUE TITLE
Status Indicator

### ISSUE THREAD

**Issue by tedivm** [github/backup-utils#127]
It would be nice if there was some sort of status indicator, especially during the "restoring repositories" portion of the restoration process (which can take hours). Even just being able to see what the last repository to be restored is would be nice, as it should show that progress is being made and the process hasn't just hung.

**Comment by rtomayko** [comment]
Agreed. @scottjg Did your progress bar work ever make it into a branch?

@tedivm One option is to use `ghe-restore -v` which will include all file transfers. Not great for progress but can definitely help with "the process hasn't just hung" concern.

**Comment by sjqnn** [comment]
any recent activity on this? would love to see a progress indicator, as its difficult to tell how long restores will take, and any indicator would be great.

**Comment by lildude** [comment]
> any recent activity on this?

Nope, but it is on our radar.

**Comment by gpadmesh** [comment]
Any recent activity? Without a status indicator, it will be difficult to know how long the restore completed or will complete?

**Comment by gpadmesh** [comment]
It will be very helpful to users running restore to have percentage completed and percentage pending either number of files and directories left to be sync to destination.

**Comment by shcorbett** [comment]
This has been implemented as part of 3.9 --> https://docs.github.com/en/enterprise-server@3.9/admin/backing-up-and-restoring-your-instance/configuring-backups-on-your-instance#monitoring-backup-or-restoration-progress

Closing out issue
