### ISSUE TITLE
Feature: Allow overriding config values on restore

### ISSUE THREAD

**Issue by rtomayko** [github/backup-utils#128]
Originally requested in https://github.com/github/backup-utils/pull/96#issuecomment-100132031:

> I'd like to make a feature request for overriding a single parameter when restoring: the hostname. The hostname is used to identify the instance within collectd - restoring a the configuration with github.example.com will mess with the monitoring setup.

It'd be a huge win to be able to override certain crucial config values on restore before a config run and without having to visit the management UI. The hostname is an obvious one but I've also wanted to toggle things like email, log collection, and snmp being enabled for staging environments.

In GHE 2.2 we moved to a new config file format that's based on [git-config(1)](http://git-scm.com/docs/git-config). If backup-utils were to add git as a dependency, we could modify the config fairly easily before restoring. The new config file format is also designed to be much more human friendly so human editing and passing a copy of the config file directly via something like `ghe-restore -f modified.conf ...` should be possible as well.

**Comment by fenixnet-net** [comment]
Bump.

We just had an outage due to not being able to do this. When restoring a production snapshot the test instances have the production hostname on the command line until the config is changed and applied.

In the process of doing that work in dev and engineer took down a production instance. They were expecting the prompt to look like a prod instance, even though it's in dev. This is extremely dangerous for obvious reasons.

**Comment by djdefi** [comment]
For an interim solution, it us possible to carefully edit the `settings.json` file as desired within the a snapshot directory prior to restoring to a test or staging appliance.

**Comment by michaelsainz** [comment]
After careful review of this request, we've determined that it would be difficult to implement this feature given how the hostname field is implemented. The restore logic doesn't account for all locations of where this field exists.

We'll continue to research ways to get similar functionality implemented into Backup-Utils - the benefit of using this against test instances and reducing risk associated with operators confusing test/dev instances vs. production is important to us.
