### ISSUE TITLE
Backups should be restorable from a single directory

### ISSUE THREAD

**Issue by tedivm** [github/backup-utils#133]
I pulled the most recent backup from our backups and attempted to run a backup. However, it seems that this utility requires the directory be named with a timestamp and have the symbolic link "current" pointed to it.

This was an easy work around, but it would be nice if I could just specify a backup directory to restore from.

**Comment by lildude** [comment]
If you backup using backup-utils, all your backup directories will be timestamps indicating the date and time when the snapshot backup was taken.

You can easily restore any one of these using the `-s [snapshot]` argument.  Any directory within the directory you have configured as your `GHE_DATA_DIR` should work.

Is this the functionality you're looking for?

**Comment by tedivm** [comment]
Can [snapshot] be an arbitrary string or is there checking that it's a timestamp?

**Comment by Xeago** [comment]
I'm not from GitHub.

I've used arbitrary strings. When setting up a new instance I `cp -a` a backup to `$NEW_INSTANCE` and then `ghe-restore -c $NEW_INSTANCE` from there. There is one step I do in between: adjust the hostname in the settings file.
