### ISSUE TITLE
Tests fail when /usr/bin/python != python2

### ISSUE THREAD

**Issue by austin987** [github/backup-utils#135]
test: ghe-backup tarball strategy ... ...                                       FAILED
    + set -e
    + sleep 1
    + GHE_BACKUP_STRATEGY=tarball
    + ghe-backup
    Starting backup of localhost:122 in snapshot 20150722T173554
    Connect localhost:122 OK (v11.10.344)
    Enabling maintenance mode on localhost:122 ...
    + exec ssh -p 122 -l admin -o BatchMode=yes localhost -- nice -n 19 ionice -c 3 '/usr/bin/env GHEBUVER=2 ghe-maintenance -s'
    + exec ssh -p 122 -l admin -o BatchMode=yes localhost -- nice -n 19 ionice -c 3 /bin/sh
    -s -X HEAD http://127.0.0.1:1337/setup/api?license_md5=fa46860931142ec6d17207c662fd2f21
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'compiler'
    test failed. last command exited with 1

compiler was removed in python3. Changing the system python interpreter to be python2 allows the tests to succeed.

Ideally the tests should work with either version.

**Comment by lildude** [comment]
Fixed with https://github.com/github/backup-utils/pull/355. Closing.
