### ISSUE TITLE
"--link-dest arg does not exist"  message for empty hookshot log directory

### ISSUE THREAD

**Issue by cjs** [github/backup-utils#137]
On the stable branch, if the backup host is using rsync > 3.0 and if the hookshot backup directory exists but is empty, the ``ghe-backup-userdata`` command fails with:

```
--link-dest arg does not exist: ../../current/hookshot
```

This shows up for users with GitHub Enterprise versions 2.2.5 and higher who don't run webhooks since the directory structure of the hookshot delivery logs changed. For 2.2.4 and below, there was a default ``logs`` subdirectory, but it's empty if there are no webhook deliveries for 2.2.5 and higher.

**Comment by mkchandler** [comment]
I know this issue has been fixed in `master` via #138, but is there going to be a release that includes it soon? If not, is it safe for me to run the `master` branch on our backup server?

**Comment by lildude** [comment]
A new release is likely to be made when GitHub Enterprise 2.4 is released later this month. There's no danger with using the current master in the meantime.
