### ISSUE TITLE
Have a separate directory for backups for each host

### ISSUE THREAD

**Issue by kylemacey** [github/backup-utils#139]
In the field, we have a customer with two instances of GitHub Enterprise. They used a single third VM to host backup utils. In order to keep the backups clear, we asked them to copy the entire directory for backup-utils and run backups from each copy. It might be easier to automatically generate a directory based off the host name.

eg:

```
$ tree data -L 2

├── github1.example.com
│   ├── 20150623T113235
│   ├── 20150623T113327
│   ├── 20150706T121824
│   ├── 20150707T141238
│   ├── 20150807T160307
│   └── current
└── github2.example.com
    ├── 20150623T113235
    ├── 20150623T113327
    ├── 20150706T121824
    ├── 20150707T141238
    ├── 20150807T160307
    └── current
```

**Comment by tedivm** [comment]
This is pretty easy to do with the [puppet module](https://forge.puppetlabs.com/tedivm/ghebackups).

**Comment by rubiojr** [comment]
@kylemacey you should be able to do that using a different backup configuration and exporting the `GHE_BACKUP_CONFIG=/path/to/backup.config` when running `ghe-backup` or `ghe-restore`.

Would that work for you?

**Comment by kylemacey** [comment]
> Would that work for you?

@rubiojr yeah! that would work perfectly, especially since this has been an edge case so far, and anything more custom than that wouldn't really seem to have paid off. Thanks!
