### ISSUE TITLE
S3 backups require that the ~/.s3cfg file exists even though its not always needed

### ISSUE THREAD

**Issue by akarnani** [github/backup-utils#151]
Newever versions of `s3cmd` are able to use the instance role for a machine in AWS instead of the configuration file.  Depending on what is in the configuration file (I haven't tested this extensively) `s3cmd` might not use the instance role.

I suggest a change to the s3 backup/restore scripts to have a flag which allows them to run w/o the config file.

**Comment by carol-hsu** [comment]
Hi 
I write a new S3 backup method #154 
It use command "aws s3 ...", so no need .s3cfg, since it is for command "s3cmd"
I also add some new features for security concerns
Feel free to try it on and give me any suggestion!

Thanks

**Comment by lildude** [comment]
All S3 backup/restore functionality and mentions within backup-utils has been removed so this issue  is now moot. Closing.
