### ISSUE TITLE
Problems with 2.5.0 release

### ISSUE THREAD

**Issue by mxk** [github/backup-utils#157]
The release was made yesterday, but the stable branch is still pointing to 2.4.0. Also, the release tarball extracts as `github-backup-utils-v2.4.0-21-g1eebd8e` and includes the full repo.

**Comment by rubiojr** [comment]
Thanks @mxk, I'm on it.

**Comment by rubiojr** [comment]
Re-uploaded the dist tarball fixing the version and excluding `.git` dir contents. Also merged master to stable.
