### ISSUE TITLE
“unknown operator” error from ghe-backup-es-audit-log

### ISSUE THREAD

**Issue by andrewdotn** [github/backup-utils#160]
I don’t know if you’d consider this issue to be under the scope of https://github.com/github/backup-utils/issues/85, but I ran into an issue upgrading the backup tools today—

On our backup server, which runs SmartOS so that we can take advantage of ZFS, `/bin/sh` is actually ksh93, which doesn’t like this line:

    if [ -f $GHE_DATA_DIR/current/audit-log/$index.gz -a $index \< $current_index ]; then

With `\<` it complains about an unknown operator; with plain `<` it tries to read from `$current_index` as a file.

I worked around this by changing the shebang to `#!/bin/bash`, and am not sure if there’s a way to get it to work in ksh93 on SmartOS.

**Comment by rubiojr** [comment]
@andrewdotn some of the scripts are already using `#!/usr/bin/env bash` to avoid compatibility issues (assuming you have bash installed). We'll probably end up doing the same for all the scripts in backup-utils. Will that work for you?

/cc @github/backup-utils

**Comment by andrewdotn** [comment]
Yup, that would work just fine.

**Comment by janorn** [comment]
This also affects solaris. Bash would solve it.

**Comment by snh** [comment]
Fixed by #177
