### ISSUE TITLE
Forced creation of parent directories breaks NAS/ISCSI shares and brings down backups

### ISSUE THREAD

**Issue by tedivm** [github/backup-utils#178]
When the snapshot directory is created it is done with the "mkdir -p" flag. This means that if any of the parent directories are missing they will be created as well.

This is a bad idea that can compound problems that occur. It is, in my experience, very common for people to backup their Github Enterprise instances to AWS Storage Gateways (although this issue can apply to any NAS or ISCSI setup). Typically a backup machine will have the storage gateway or nas mapped to a specific folder (such as /backups/) with the github backups being a sub folder of that (ie, /backups/github).

Sometimes NAS's go down. AWS requires maintenance on their machines which occasionally involves rebooting them. When this occurs the shared folders on the backup machine disappear.

While those folders are gone most backup programs will spit out an error stating that the destination is inaccessible. Instead this backup-utils program just ignored the error condition and recreates the missing directories. Then when the remote storage is available again it can no longer mount it due to the folder it wants to mount it to containing files. If other backups are being placed on that same drive then this utility just managed to break all of them.

The proper solution when parent directories are unavailable is to spit out an error. This way the actual problem (the parent directory disappearing) can be dealt with instead of covered up.

**Comment by tedivm** [comment]
The [offending line](https://github.com/github/backup-utils/blob/master/bin/ghe-backup#L21).

**Comment by rubiojr** [comment]
@tedivm that's a good point, but we'll be changing the behaviour that some people or tools may rely on. We could add an optional flag to avoid creating it and warn when creating the directory also, if that helps.

**Comment by tedivm** [comment]
That works for me.

**Comment by tedivm** [comment]
Bump.

**Comment by rubiojr** [comment]
@tedivm https://github.com/github/backup-utils/pull/186 should address this.
