### ISSUE TITLE
Issues with ps on Solaris

### ISSUE THREAD

**Issue by janorn** [github/backup-utils#184]
In [ghe-backup you use ps -p <pid> -o command=](https://github.com/github/backup-utils/blob/c0b0244837bca5a4e67597843599f888d36d5a02/bin/ghe-backup#L69) to check if there already is a running backup process. This command will fail on Solaris as the syntax on solaris is:

ps -p <pid> -o comm=

**Comment by lildude** [comment]
The use of ps has evolved quite a bit since this issue was opened and https://github.com/github/backup-utils/pull/435 now goes the route of completely ignoring formatting or options and passes the responsibility of checking the process to the admin.

As such I think we can mark this as resolved.
