### ISSUE TITLE
host keys are not restored under ghe cluster environment

### ISSUE THREAD

**Issue by shawnzhu** [github/backup-utils#226]
@gnawhleinad pointed out that it doesn't restore host keys in cluster environment: [ghe-restore#L314-L317](https://github.com/github/backup-utils/blob/f7a401e30d8db3a20e4211482a3928c8f3476555/bin/ghe-restore#L314-L317).

If the host keys under `/data/user/common` are used by babeld process only, there is **no** difference between a cluster environment and a single appliance. since all `web-server` roles on frontend nodes must serve the same host key for all users.

**Comment by docwhat** [comment]
I cannot express how disruptive it is to have to fix the `known_hosts` for all the build systems, users, etc. when it changes.

**Comment by gnawhleinad** [comment]
For clarification, this issue exists only on a restore to a GitHub Enterprise clustering environment.

--

> I cannot express how disruptive it is to have to fix the known_hosts for all the build systems, users, etc. when it changes.

:sparkles:, I agree - and we've been working with @shawnzhu. This issue is important to us and we're working on a fix.

**Comment by shawnzhu** [comment]
I will close this once #228 works for me in GHE cluster.

**Comment by shawnzhu** [comment]
it works! Thanks
