### ISSUE TITLE
`readlink -f` not supported on OS X

### ISSUE THREAD

**Issue by terrorobe** [github/backup-utils#255]
The leaked ssh key check introduced a [call to `readlink -f`](https://github.com/github/backup-utils/blob/28c01a09565815363e208a8e6e95c3a48cff8eb7/share/github-backup-utils/ghe-detect-leaked-ssh-keys#L66) which isn't supported on OS X:

```
Completed backup of 192.168.178.120:122 in snapshot 20160926T160227 at 16:02:38
Checking for leaked ssh keys ...
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by GlobalizationIntlAgentOnBangladesh** [comment]
Any difficult the sultion for working team.

**Comment by GlobalizationIntlAgentOnBangladesh** [comment]
Globalization International Expert Major Gurop On Bangladesh.

**Comment by lildude** [comment]
Closing as you fixed this in https://github.com/github/backup-utils/pull/256 😉.
