### ISSUE TITLE
ghe-import-passwords not present in GHE 2.8.6

### ISSUE THREAD

**Issue by georgewilliamherbert** [github/backup-utils#282]
The share/github-backup-utils/ghe-restore-settings script uses the GHE server script "ghe-import-passwords" to do some work.  That script is not present in the GitHub Enterprise servers I have built with GHE 2.8.x (2.8.6 mostly).  I haven't found a doc on when it was deleted or what an acceptable alternate is yet, but restores fail rapidly.  The backups seem to run fine but I can't verify that by doing a restore test.

On my GHE 2.8.6 server doing ls in /usr/local/bin I find the following:
admin@ghe-prod-upgrade-286:/usr/local/bin$ ls
ghe-announce                       ghe-export-ssh-host-keys        ghe-set-password
ghe-btop                           ghe-export-ssl-ca-certificates  ghe-setup-network
ghe-check-disk-usage               ghe-git-janitor                 ghe-spokes
ghe-cleanup-caches                 ghe-hook-env-create             ghe-ssh-check-host-keys
ghe-cleanup-settings               ghe-import-authorized-keys      ghe-ssh-roll-host-keys
ghe-cluster-config-apply           ghe-import-license              ghe-ssl-ca-certificate-install
ghe-cluster-config-check           ghe-import-mysql                ghe-storage
ghe-cluster-config-init            ghe-import-redis                ghe-storage-extend
ghe-cluster-diagnostics            ghe-import-settings             ghe-support-bundle
ghe-cluster-each                   ghe-import-ssh-host-keys        ghe-system-info
ghe-cluster-maintenance            ghe-import-ssl-ca-certificates  ghe-update-check
ghe-cluster-nodes                  ghe-logs-tail                   ghe-upgrade
ghe-cluster-set-password           ghe-maintenance                 ghe-user-csv
ghe-cluster-status                 ghe-memcache-switch-external    ghe-user-demote
ghe-cluster-support-bundle         ghe-migrator                    ghe-user-promote
ghe-config                         ghe-mysql-switch-external       ghe-user-suspend
ghe-config-apply                   ghe-negotiate-version           ghe-user-unsuspend
ghe-config-check                   ghe-org-admin-promote           ghe-webhook-logs
ghe-console                        ghe-reactivate-admin-login      github-env
ghe-data-quality-check             ghe-redis-switch-external       git-import-detect
ghe-dbconsole                      ghe-repl-promote                git-import-filter-fast-import
ghe-diagnostics                    ghe-repl-setup                  git-import-git-raw
ghe-diagnostics-io                 ghe-repl-start                  git-import-hg-raw
ghe-dpages                         ghe-repl-status                 git-import-rewrite
ghe-elasticsearch-switch-external  ghe-repl-stop                   git-import-svn-raw
ghe-es-wait-for-green              ghe-repl-teardown               git-import-tfs-raw
ghe-export-authorized-keys         ghe-repo                        hookshot-env
ghe-export-graphs                  ghe-repo-gc                     mysql-systemd
ghe-export-mysql                   ghe-resque-info                 node
ghe-export-redis                   ghe-rollback-rootfs             ruby
ghe-export-settings                ghe-service-list
admin@ghe-prod-upgrade-286:/usr/local/bin$

It was present on our former 2.0.0 server (and test 2.0.0 boxes) but not 2.8.6.

**Comment by jatoben** [comment]
@georgewilliamherbert Are you restoring a backup of your GitHub Enterprise 2.0 appliance to the 2.8.6 instance? Restoring backups follows [the same versioning rules as upgrades do](https://help.github.com/enterprise/2.7/admin/guides/installation/upgrading-the-github-enterprise-virtual-machine/#upgrading-from-github-enterprise-2x) — specifically, skipping more than one feature release isn't supported.

If you're working on testing the upgrade process, please feel free to open a support ticket at https://enterprise.github.com/support and we can help you with the details.

**Comment by georgewilliamherbert** [comment]
I'm checking, it was supposed to be a 2.8.6 backup but it's possible we had a misconfiguration I missed.

**Comment by georgewilliamherbert** [comment]
Just confirming - we had a complicated configuration issue unrelated to backup utility itself, that caused it to have backed up a 2.0.0 host when we thought it had the new 2.8.6 host.  Closing, not an actual issue.
