### ISSUE TITLE
criteria to verify a backup snapshot from github/backup-utils is restorable

### ISSUE THREAD

**Issue by shawnzhu** [github/backup-utils#295]
## Scenario

Given a GHE cluster, run the command `ghe-backup` to backup all data in a new snapshot. It requires a verification step to make sure the backup snapshot is restorable after the command is executed.

## Ideas

1. we can do `ghe-restore` to see if it can restore to a running GHE appliance/cluster successfully but it will take a long time when there are ~100k git repos.
2. create a new command to check data integrity like checks all Git repos are in backup snapshot.

## Question

If it restores a backup snapshot from a GHE cluster to a single GHE appliance, does it mean it this backup snapshot can be restored to a GHE cluster?

**Comment by snh** [comment]
Cluster backup snapshots are not restorable to a single appliance at this time, and are [blocked by ghe-restore](https://github.com/github/backup-utils/blob/dda0147561f641d47cae9ff9984eb204156b5d8b/bin/ghe-restore#L100-L105) as a result.

In-built functionality to verify the integrity of a snapshot, post backup, also doesn't exist at this time.

For now, monitoring the console output from `ghe-backup`, in combination with periodic test restores to a test cluster, remains our recommended approach for verifying the integrity of backup snapshots.
