### ISSUE TITLE
Restore should run at higher priority than backup (or at least be separately configurable)

### ISSUE THREAD

**Issue by OptimusAl** [github/backup-utils#307]
Right now, for both backup and restore, the nice level is set in share/github-backup-utils/ghe-backup-config  the same for both backup and restore to a very low priority level.

The default settings are the lowest:  

\# CPU and IO throttling to keep backups and restores from thrashing around.
${GHE_NICE:="nice -n 19"}
${GHE_IONICE:="ionice -c 3"}

This makes sense for a backup but a restore is happening on a box in maintenance mode.  We want the restore to finish quickly. I can't think of anything else my github appliance ought to be doing that would be more important than completing the restore. 

 I have found by setting the value of ionice to 2 and nice to 1, our restores are completing twice as fast.

But I don't see an easy way to set it separately for both backup and restore, meaning if I ran a backup with that installation it would thrash my instance.

**Comment by lildude** [comment]
@OptimusAl The prioritisation is so we don't overwhelm your backup host.

If you want to bump the priority of the restore, you can prefix the `bin/ghe-restore` command with `GHE_NICE` and `GHE_IONICE` variables set to the priority you'd prefer.
