### ISSUE TITLE
Need of verification for organisations in Github

### ISSUE THREAD

**Issue by kvnamipara** [github/backup-utils#309]
Anyone can make organisations with names of big tech giants in the industry. There is need of organisation verification similar to how twitter and instagram verify celebrities and official accounts.

**Comment by rubiojr** [comment]
@kvnamipara: is that feedback for GitHub? This repo is for the tools to backup GitHub Enterprise appliances.

**Comment by kvnamipara** [comment]
@rubiojr yes it is just feedback. how to give feedback? thanks

**Comment by rubiojr** [comment]
I'll ask around and let you know.

**Comment by rubiojr** [comment]
@kvnamipara please use https://github.com/contact. The feedback should go in the right place.

Thanks!
