### ISSUE TITLE
Built in support for warm DR standby

### ISSUE THREAD

**Issue by rtomayko** [github/backup-utils#33]
Setting up a warm standby VM is currently fairly straightforward once basic backups are in place but could benefit from built in support in github/backup-utils. The basic idea is to configure a new VM (possibly in another DC) and leave it in maintenance mode. Then modify the scheduled backup run to use the following instead of just `ghe-backup`:

```
ghe-backup && ghe-restore <standby-ip>
```

The Git backup and restore portions are fully incremental so this should be efficient enough to schedule as regularly as every hour, bringing the RPO down to an acceptable level. The RTO could be as low as minutes with a warm standby VM, or could be ~1 hour if people prefer to opt for a cold / provision-VM-at-time-of-recovery setup. Both options should be available and the choice will be based on how much cash / operational work people want to take on vs. optimizing the RPO/RTO. No changes to the current 11.10.343 release are necessary for this.

---

I ran through the basic process of setting up a warm standby VM yesterday and wanted to document the process. Let's assume the primary GHE instance is at "github.example.com". The process for setting up a standby is:
1. Run `ghe-backup` against the primary to get a first successful snapshot.
2. Boot a new 11.10.320 VM to act as the standby and record the `<standby-ip>`.
3. Create a DNS entry: "github-standby.example.com" pointed to `<standby-ip>`. This should be set with a low TTL (like 5 minutes). The main "github.example.com" DNS entry should also have a low TTL.
4. Upload license and 11.10.342 GHP to the standby VM via http://github-standby.example.com/setup.
5. Add the backup site SSH key to authorized keys in manage http://github-standby.example.com/setup/settings.
6. Run `ghe-standby github-standby.example.com` ([WIP version here](https://github.com/github/backup-utils/blob/ghe-standby-control/scripts/ghe-standby)) from the backup site. This is essentially `ghe-maintenance -s && ghe-import-settings && sudo enterprise-configure` on the remote side. It puts the standby in maintenance mode and loads in settings from the last snapshot. The standby VM will stay in maintenance mode until it's activated.
7. Should also run `ghe-import-ssh-host-keys` here but that changes the host key signature and will cause excessive SSH warnings and prompts. We can find a way to fit this into the `ghe-standby` script sanely.
8. Perform an initial restore of the latest snapshot with `ghe-restore github-standby.example.com`.
9. Schedule the backup run as `ghe-backup && ghe-restore github-standby.example.com`.

At this point, we have backups being taken and loaded into the standby on a regular basis. The process for recovery / failing over is:
1. Put the primary instance in maintenance mode (if it's still up and available).
2. Take the standby instance out of maintenance mode. I have a WIP `ghe-activate github-standby.example.com` [script going here](https://github.com/github/backup-utils/blob/ghe-standby-control/scripts/ghe-activate). This just takes the standby instance out of maintenance mode via `ghe-maintenance -u`.
3. Check that https://github-standby.example.com is up and working.
4. Point github.example.com DNS to `<standby-ip>`.
5. Point github-standby.example.com DNS to the old primary if it should take over as the standby host. If it's borked, start at the beginning and set up a new standby VM.

**Comment by 236084298** [comment]
https://github.com/github/backup-utils/issues/437#issuecomment-518073909https://github.com/github/backup-utils/issues/33#issuecomment-55071544https://github.com/github/backup-utils/issues/33#issuecomment-66915789https://github.com/github/backup-utils/issues/33#issuecomment-66919946

**Comment by shcorbett** [comment]
Since this issue is almost 9 years old - closing this out but have referenced this in our longer term initiatives to see if this is viable or not
