### ISSUE TITLE
Backup fails if the exact command `sha256sum` is not found

### ISSUE THREAD

**Issue by preposthuman** [github/backup-utils#334]
Backup fails if the exact command `sha256sum` is not found. 
```Starting backup of GitHub.int.****.com in snapshot 20170914T105717
/Users/****/repos/ghe-backup-utils/share/github-backup-utils/ghe-ssh: line 61: sha256sum: command not found
This port is reserved for git operations.
To administer the host over SSH, use port 122 with `ssh -p 122`.
```
This didn't happen yesterday, and appears to be caused by the changes since yesterday.
I have a ssh config to use the standard admin port. 
I run the same commands every day:
```~/repos/ghe-backup-utils $ cd ~/repos/ghe-backup-utils/; git pull origin stable ; bin/ghe-backup ; du -chs /Users/****/repos/ghe-data-backup/data/*```
The results for this latest backup show directory's content size of zero bytes.

MacOS does not include the `sha256sum` command by default, and none is found using `brew search sha256sum`. On the Mac, the equivalent command is `shasum -a 256 [FILE]`.

**Comment by snh** [comment]
Thanks for the report @preposthuman!

I've opened #335 to switch over to `md5sum` here, as this is more widely universally available.

In the meantime, you can work around this issue by installing the `coreutils` homebrew package with `brew install coreutils`, and adding `/usr/local/opt/coreutils/libexec/gnubin` to your path when running the backup utilities. Please let us know how you go with this workaround.
