### ISSUE TITLE
v2.11.0 release note tweak suggestion

### ISSUE THREAD

**Issue by lowply** [github/backup-utils#339]
[Release GitHub Enterprise Backup Utilities v2.11.0](https://github.com/github/backup-utils/releases/tag/v2.11.0) says:

> Ensure restores of backups of 2.9 and 2.10 have undergone the audit log migration as detailed at https://git.io/v5rCE. This is required to support restoring to GitHub Enterprise 2.11.0 #329

But this sounds a bit confusing. How about changing it to:

> Ensure restores of backups of 2.9 and 2.10 have undergone the [audit log migration](https://help.github.com/enterprise/2.10/admin/guides/installation/migrating-audit-logs-to-github-enterprise-2-11/), when restoring to GitHub Enterprise 2.11.0 and above. #329

Assigning @lildude as you've released it.

**Comment by lildude** [comment]
Done. Thanks for the nicer wording.
