### ISSUE TITLE
Release for GitHub Enterprise 2.12+?

### ISSUE THREAD

**Issue by mdwheele** [github/backup-utils#371]
Hello!

The [Backups and disaster recovery](https://help.github.com/enterprise/2.12/admin/guides/installation/backups-and-disaster-recovery/) documentation for GitHub Enterprise 2.12 instruct to use the "latest release" of `backup-utils`. It seems that historically, the release versions have followed closely with the supported version of GitHub Enterprise. 

Is this simply a coincidence that they happen to have matched? We're running `backup-utils@v2.11.2` on our instance (2.12.5) and things seem to be rolling fine. I have faint memory of reading that Enterprise will always support one version behind current for `backup-utils`, but I can't find that now. 

Anywho, I'm more or less looking for some clarification on how the release process works. If it can be explicated here, I'd be willing to contribute some documentation if you think it'd be helpful.

**Comment by lildude** [comment]
Yes, for the most part is has been a coincidence that the version numbers have matched historically. We've tended to only bump the major version in line with the GHE release if there is a requirement for it in that GHE release, hence we've skipped entire major versions in the past.

That said, we are due another patch release which I plan to do tomorrow. The next major release will likely coincide with the 2.13 release and will be quite significant, with a significant improvement in the documentation too.

Regarding support, the two versions thing is regarding the number of "steps" we support for upgrades and restores of GHE as opposed to backup-utils itself eg we'll support upgrading from 2.9 directly to 2.11 but not to 2.12 as that is three steps. The same thing for restores: you can restore a backup of a 2.9 instance to 2.11 but not 2.12, regardless of the version of backup-utils provided that version supports both versions.

**Comment by mdwheele** [comment]
Sounds good. So in theory, staying current with latest release of Enterprise and `backup-utils` should be good enough then?

**Comment by lildude** [comment]
> Sounds good. So in theory, staying current with latest release of Enterprise and backup-utils should be good enough then?

Yup. If a specific release of backup-utils is ever needed, it'll be in the Enterprise release notes for that release and also forced (and reported if not met) through the version check that happens early in the backup and restore process.

**Comment by lildude** [comment]
To close this out, here's the note I added to the [2.13.0 release](https://github.com/github/backup-utils/releases/tag/v2.13.0) as an indicator of the way we'll be doing things in future:

> Note: Starting with Backup Utilities v2.13.0, version support is inline with that of the GitHub Enterprise upgrade requirements and as such, support is limited to three versions of GitHub Enterprise: the version that corresponds with the version of Backup Utilities, and the two releases prior to it.
> 
> For example, Backup Utilities 2.13.0 can be used to backup and restore all patch releases from 2.11.0 to the latest patch release of GitHub Enterprise 2.13. Backup utilities 2.14.0 will be released when GitHub Enterprise 2.14.0 is released and will then be used to backup all releases of GitHub Enterprise from 2.12.0 to the latest patch release of GitHub Enterprise 2.14.
> 
> Backup Utilities 2.11.4 and earlier, and the legacy branch, offer support for GitHub Enterprise 2.10 and earlier releases.
