### ISSUE TITLE
ghe-restore allows restoring onto an invalid older version of the app.

### ISSUE THREAD

**Issue by catscanner** [github/backup-utils#403]
There appear to be no checks run on the target host before a backup is restored.

Using GitHub backup-utils v2.13.0 I was able to restore into a Github app running 2.12.9

This left us with an instance that was able to display home pages, but 500s when clicking on any repo.

We were able to 'fix forward' by updating the application and replica instance, but that involved several manual steps including scping install images onto hosts as the automated tools declined to run.

Ideally we would have preferred the backup tools to refused to restore based on the mis-match between the backed up version and the running version on the target.

I would expect a -f to force a restore.

Had we been alerted it would have been much faster and easier to redeploy our stack at the correct version before restoring the data.

**Comment by catscanner** [comment]
The backup was taken from a 2.13.1 instance.
It was that the target appliance was older than the backup instance, yet the restore took place that took me by surprise. I had expected it to fail with an error.

**Comment by snh** [comment]
> It was that the target appliance was older than the backup instance, yet the restore took place that took me by surprise. I had expected it to fail with an error.

That is certainly something we could consider detecting and blocking then, as it isn't supported nor expected to work due to the data migrations that occur between feature releases.

Thank you for raising this, I've added a number of labels to this issue to help us track this as a possible enhancement.
