### ISSUE TITLE
Add support for storing hourly, daily, monthly backups

### ISSUE THREAD

**Issue by areitz-stripe** [github/backup-utils#405]
Hi,

We run `ghe-backup` from cron hourly on our backup server, and we keep around ~70 backups, which means that we only have ~3 days of backups on hand to do a restore. I'd prefer to keep some older backups around, and a lower granularity. I'm thinking of a scheme such as this:

```
$GHE_DATA_DIR/hourly
$GHE_DATA_DIR/daily
$GHE_DATA_DIR/monthly
```

The first directory would contain 24 backups, the second one would contain 30, and the last directory would contain 12. This would let me cover easy restores for a whole year, at increasingly lower granularity. In the config, there would be corresponding variables to control the exact number of backups that would be stored at each level.

If this seems like an idea that would be accepted, I can take a look at crafting a PR. Thanks!

**Comment by lildude** [comment]
I don't think we really need this as part of Backup Utilities as this is already achievable the way things stand. It would also add potentially unneeded complexity.

To achieve what you want, you can use three different cron jobs with three different configuration files with appropriately set `GHE_DATA_DIR` and `GHE_NUM_SNAPSHOTS` options in each:

```
GHE_BACKUP_CONFIG=backup.config-hourly /path/to/backup-utils/bin/ghe-backup -v
GHE_BACKUP_CONFIG=backup.config-daily /path/to/backup-utils/bin/ghe-backup -v
GHE_BACKUP_CONFIG=backup.config-monthly /path/to/backup-utils/bin/ghe-backup -v
```

Or three different cron jobs with a single "base" configuration file (assuming default location in the following examples), and then use environment variables to override certain options specific to each cron job:

```
GHE_NUM_SNAPSHOTS=23 GHE_DATA_DIR=/path/to/data/hourly /path/to/backup-utils/bin/ghe-backup -v  # 23 because the 24th would be the first daily
GHE_NUM_SNAPSHOTS=29 GHE_DATA_DIR=/path/to/data/daily /path/to/backup-utils/bin/ghe-backup -v # 29 because the 30th would be the first monthly
GHE_NUM_SNAPSHOTS=12 GHE_DATA_DIR=/path/to/data/monthly /path/to/backup-utils/bin/ghe-backup -v
```

Depending on your backup host, you can either explicitly state the times etc in the crontab or add scripts to the relevant `/etc/cron.d/hourly`, `/etc/cron.d/daily` and `/etc/cron.d/monthly` directories.

An alternative solution is to use an hourly schedule and then setup another cronjob that runs a script at the desired intervals that creates a tarball (ensuring symlinks are retained) of the snapshot directory and then does something like store it in the desired daily and monthly directories or uploads it to somewhere offsite like AWS S3.

**Comment by loolloveta** [comment]
[rfc7841.txt.pdf](https://github.com/github/backup-utils/files/2087516/rfc7841.txt.pdf)

**Comment by areitz-stripe** [comment]
Hi @lildude, thanks for the comment. Wasn't aware of the environment variables, I think that will work for my purpose. Thanks!
