### ISSUE TITLE
ghe-restore output is not completed

### ISSUE THREAD

**Issue by erezsh-lp** [github/backup-utils#412]
while running ".../backup-utils/bin/ghe-restore -f" although it is finished it don't print "Completed restore of ... " as before. Instead it stack on "Configuring appliance.." and ends there.
Nevertheless, the restore appears to be ok .

The output appears as follow:
Restoring Redis database ...
Restoring Git repositories and Gists ...
Restoring GitHub Pages ...
Restoring SSH authorized keys ...
Restoring storage data ...
Restoring custom Git hooks ...
Restoring Elasticsearch indices ...
Configuring appliance ...

**Comment by lildude** [comment]
Hmmm, this sounds like something may have gone wrong whilst applying the settings in the "Configuring appliance" step.

Do you get anymore information if you use `bin/ghe-restore -f -v`?

What versions of Backup Utilities and GitHub Enterprise are involved?

**Comment by lildude** [comment]
Come to think of it, it's probably best to contact our support team via https://enterprise.github.com/support as this may need some back-and-forth and information that probably shouldn't be shared in a public location.

**Comment by lildude** [comment]
From the silence on this issue, I'm going to take it this has been addressed via our support team so I'm closing this issue.
