### ISSUE TITLE
Rename the repository to "ghe-backup-utils"

### ISSUE THREAD

**Issue by nkadel** [github/backup-utils#428]
Since all the components of it have "ghe" as a prefix, it would help clarify what the software is and what it is for if the repository were named "ghe-backup-utils"

Renaming a github hosted repo can be confusing, but a link is left behind in Github's metadata that connects queries to the old URL to the new repo, so it does not normally break anything to do a rename. Only if the owner creates a new repository of the same name as the old repo does it get..... wonky.

**Comment by lildude** [comment]
I'm not sure what the benefit of renaming the repo would be - whilst all the commands are prefixed with `ghe-`, all the documentation, descriptions etc clearly indicate the purpose of the repository.

**Comment by nkadel** [comment]
What is the benefit of it being called a general name like "backup-utils"? Because they're certainly not useful for anything but "GitHub Enterprise", or ghe.  To package it, for example to publish it as a deb or rpm package or to manage it with chef or ansible, it would help make packaging more clear, and name the bundle or packge consistently with its included binaries.

It's functional as-is, but I think it would be more clear as ghe specific tools if it were labeled specifically "ghe-backkup-utils"

**Comment by lildude** [comment]
Thank you for your explanation. We have a lot of internal tooling and documentation that depend on the current repository name and it's a large effort to change these with little obvious or substantive overall benefits. This is also potentially unnecessarily disruptive to our customers.

As for packaging, a different package name can be used for the package at the time of generation: we do it when we build the backup-utils Debian package. Similar "aliasing" can be performed elsewhere too.
