### ISSUE TITLE
Do not use "dirname/../share" syntax

### ISSUE THREAD

**Issue by nkadel** [github/backup-utils#429]
The syntax for "$( dirname "${BASH_SOURCE[0]}" )/../share/github-backup-utils/ghe-backup-config" is confusing and potentially erroneous. If the "${BASH_SOURCE[0]}" ) is in the top level of a symlinked directory, the "../" will resolve to the directory of the target of the symlink, not the source of the symlink. It's also confusing to read.

**Comment by lildude** [comment]
Teeny nit: this relies upon a GNU-ism: `--canonicalize` is specific to GNU readlink and isn't available on macOS, for example. We try not to add small requirements like this if we can avoid it.

I think it also unnecessarily calls `dirname` twice.

Ignoring potential confusion and aesthetics, what problem are you encountering with the current code that is preventing it from working?

In the OP, you mentioned:

> If the "${BASH_SOURCE[0]}" ) is in the top level of a symlinked directory, the "../" will resolve to the directory of the target of the symlink, not the source of the symlink.

But I'm not sure how this is a problem as the symlink will be followed when sourcing the file.

I created a `backup-utils/bin/ghe-foo` containing:

```bash
#!/usr/bin/env bash
echo "$( dirname "${BASH_SOURCE[0]}" )/../share/github-backup-utils/ghe-backup-config"
. "$( dirname "${BASH_SOURCE[0]}" )/../share/github-backup-utils/ghe-backup-config"
env | grep GHE_
```

.. and tested with this, and it has the desired outcome, regardless of where I call it and the symlinks involved:

```
$ backup-utils/bin/ghe-foo
backup-utils/bin/../share/github-backup-utils/ghe-backup-config
GHE_SNAPSHOT_TIMESTAMP=20180911T155644
GHE_SNAPSHOT_DIR=/tmp/backup-utils/data/20180911T155644
$ ln -s backup-utils ano-loc
$ ano-loc/bin/ghe-foo
ano-loc/bin/../share/github-backup-utils/ghe-backup-config
GHE_SNAPSHOT_TIMESTAMP=20180911T155659
GHE_SNAPSHOT_DIR=/tmp/ano-loc/data/20180911T155659
$ cd backup-utils
$ bin/ghe-foo
bin/../share/github-backup-utils/ghe-backup-config
GHE_SNAPSHOT_TIMESTAMP=20180911T155709
GHE_SNAPSHOT_DIR=/tmp/backup-utils/data/20180911T155709
$ cd bin     
$ ./ghe-foo
./../share/github-backup-utils/ghe-backup-config
GHE_SNAPSHOT_TIMESTAMP=20180911T155716
GHE_SNAPSHOT_DIR=/tmp/backup-utils/data/20180911T155716
$ cd ../../ano-loc
$ bin/ghe-foo     
bin/../share/github-backup-utils/ghe-backup-config
GHE_SNAPSHOT_TIMESTAMP=20180911T155725
GHE_SNAPSHOT_DIR=/tmp/ano-loc/data/20180911T155725
$ cd bin          
$ ./ghe-foo   
./../share/github-backup-utils/ghe-backup-config
GHE_SNAPSHOT_TIMESTAMP=20180911T155729
GHE_SNAPSHOT_DIR=/tmp/ano-loc/data/20180911T155729
$
```

I have `GHE_SNAPSHOT_DIR=data` in my `backup.config`.

**Comment by nkadel** [comment]
I'm going to withdraw this concern. : manipulating the "dirname" commands to do a cleaner task of this would just add unnecessary complexity.
