### ISSUE TITLE
About the feature for cleaning up stale nodes.

### ISSUE THREAD

**Issue by pnsk** [github/backup-utils#430]
Hello 👋 

In the [2.13.2](https://github.com/github/backup-utils/releases/tag/v2.13.2) or later, the following feature's been published:

> Clean up stale HA nodes on restore #396

Cleaning up stale nodes during restore is a great feature because it'll avoid a problem caused by stale nodes.

For example, GHE users normally configure HA configuration. On the situation, when a user upgrades their instance with like:

1. Configure a new GHE instance of new version.
2. Restore with `ghe-restore` command, the backup data from a primary instance which has replication settings, to a new version instance created on step1.
3. Configure a new HA configuration on the instance created with above steps, with a new replica instance.

Stale nodes like old replica info will be often problem on step3.  There'll be CRITICAL or WARNING messages in the output of the replication status.

However, I think `$instance_configured` is normally `false` in the process of restore. That means normally stales nodes won't be cleaned up:

https://github.com/github/backup-utils/blob/5ea6eb3d87474a162f2f8982681a63ce77abae8c/bin/ghe-restore#L345

(I understand why the condition was added. ref: https://github.com/github/backup-utils/commit/02310de00f54d85df79255262691d28a47a9648f)

To clean up stale nodes on a GitHub Enterprise instance, users need to go restore with the following steps:

1. Configure a new instance.
2. Choose “New Install” instead of “Migration”.
3. Push the "Save settings" button at management console.
4. Then restore with the `ghe-restore -c` command. (The `-c` option will overwrite the settings. )

I think above steps are not normal way for users 🤔 

Are there any other idea for users to remove stale nodes from the instance without overwriting the settings?

cc/ @jatoben @taz @doublemarket

**Comment by lildude** [comment]
> Are there any other idea for users to remove stale nodes from the instance without overwriting the settings?

Unfortunately, not. From https://github.com/github/backup-utils/pull/409 in which I implemented the requirement for the instance to be configured:

> Unconfigured instances may have pending database migrations that could cause the required database queries to fail. We can't predict which migrations will affect the cleanup so the best option is to not run them on unconfigured instances.
> 
> Future work will look into how we can best perform this cleanup when restoring to unconfigured nodes. In the mean time, a manual cleanup can be performed later, if need be.

That manual cleanup would be to run `/usr/local/share/enterprise/ghe-cluster-cleanup-node <UUID>` for all the nodes that need to be removed after restoring.

**Comment by pnsk** [comment]
@lildude Thank you for your reply 😄 I understood why we need to configure the instance.
I'm closing this issue 💡
