### ISSUE TITLE
Provide links, maybe even documentation, about SSH key handling

### ISSUE THREAD

**Issue by nkadel** [github/backup-utils#431]
Since Github Enterprise hosts have very controlled SSH access, they require activation of an administrative SSH public key for this backup software to work. But this key typically provides both read and write access, which can be very dangerous.

Some links to the SSH key management pages for Github Enterprise in the documentation would be helpful. Even more helpful would be notes to wrap the keys in "ForceCommand" directives, to even further restrict operations to read-only, much like the old "valide-rsync.sh" wrapper described at https://www.linux.com/news/making-secure-remote-backups-rsync . I used to use that tool with great success with "rsnapshot", it might be very useful for this as well.

**Comment by lildude** [comment]
> Some links to the SSH key management pages for Github Enterprise in the documentation would be helpful.

There already is... https://github.com/github/backup-utils/blob/master/docs/getting-started.md links to https://enterprise.github.com/help/articles/adding-an-ssh-key-for-shell-access . 

That documentation could however be enhanced to detail scoping of keys.

**Comment by nkadel** [comment]
Man I was making typos yesterday. I meant to suggest using "validate-rsync.sh", not "valide-rsync.sh". Let me see if I can gain access to a GHE server this weekend to test that kind of detailed scoping.

**Comment by nkadel** [comment]
validate-rsync.sh won't work well due to the need for other shell commands, run through ghe-ssh. But restricting it to only allow access from specific hosts would be a start.

**Comment by nkadel** [comment]
I've reached out to Github about improving that upstream documentation.

**Comment by lildude** [comment]
> I've reached out to Github about improving that upstream documentation.

Great! Thanks. I guess we don't need this issue anymore. Closing.
