### ISSUE TITLE
Option to put backups into archive (.tar.gz or equivalent)

### ISSUE THREAD

**Issue by itssimple** [github/backup-utils#432]
To make it easier on rsync with hourly backups from `ghe-backup`, would it be possible to add a option to compress the backups once it's done?

**Comment by lildude** [comment]
Can you provide a bit more context as to what you're ultimately trying to acheive as backing up to a tarball or other archive format would mean we couldn't take advatange of the hardlinks that are currently used to manage the snapshots and reduce the amount of data backed up each time.

**Comment by lildude** [comment]
I have a hunch so I'm going to refer you to a previous discussion in https://github.com/github/backup-utils/issues/259 which may be relevant.

**Comment by itssimple** [comment]
Yeah, it seems like a relevant discussion, we have the backup working to our on-site backup machine, but we want to store it on our off-site as well. And building the partial file list increases in time as new snapshots are added.

Would it be possible, that I compress all the snapshots + current-folder into a tarball and copy that perhaps?

**Comment by lildude** [comment]
> Would it be possible, that I compress all the snapshots + current-folder into a tarball and copy that perhaps?

That would certainly do the trick. Once the `ghe-backup` has finished running, you can do as you please with the snapshots. 

You could also tar just the current folder. As we use hardlinks, it'll include the latest version of every file. 

The downside with this is you'll be transferring all the files and not just those that have changed between snapshots.

One method around this would be to replicate the data directory structure on your off-site host and use rsync with the `--link-dest=DIR` option (it's what we use in backup-utils). Once the initial transfer has finished, all subsequent rsyncs should only transfer those files that have changed.

The first option will spend more time building and transferring the archive at the expense of transferring a lot of potentially duplicate data, whilst the second will spend more time building the file list and transferring just the files that have changed at the expense it may take slightly longer.

**Comment by itssimple** [comment]
Ah, ok. Thanks a bunch! This will make things easier for our off-site copy.
We'll just keep the `current` folder off-site.
