### ISSUE TITLE
Provide script for rotating and pruning backups

### ISSUE THREAD

**Issue by nkadel** [github/backup-utils#437]
Few people want or need to keep all backups of a system.  If they do hourly backups, they often want to expire anything older than a day and preserve a week of daily backups, expire those and keep a month of weekly backups, etc. A wrapper script to auto-expire the backups would be useful, even if it means moving those daily or weekly or monthly backups to different folders.

**Comment by lildude** [comment]
We don't think we really need this as part of Backup Utilities as this is already achievable the way things stand. It would also add potentially unneeded complexity. See my explanation at https://github.com/github/backup-utils/issues/405#issuecomment-390136612 for details on how you can do this yourself.

**Comment by 236084298** [comment]
.dockerignore

**Comment by 236084298** [comment]
https://github.com/github/backup-utils/issues/437#issuecomment-420309693
