### ISSUE TITLE
Document disabling of GC operations/maintenance queue

### ISSUE THREAD

**Issue by MrChrisW** [github/backup-utils#440]
### Overview

The question of whether backup-utils stops maintenance/GC operations on GHE comes up frequently, often the easiest way to confirm this, is to look at the self-documenting code + comments:

https://github.com/github/backup-utils/blob/6136922ebad137cbacf54ede335c8e4dbda880f4/share/github-backup-utils/ghe-backup-config#L186-L187

https://github.com/github/backup-utils/blob/6136922ebad137cbacf54ede335c8e4dbda880f4/share/github-backup-utils/ghe-gc-disable#L35-L39

### Problem

Viewing the code to determine the application behaviour isn't efficient.

### Solution

Document the fact maintenance/GC operations are paused when backup-utils is running. Preferably in the FAQ: https://github.com/github/backup-utils/blob/master/docs/faq.md

**Comment by snh** [comment]
> Document the fact maintenance/GC operations are paused when backup-utils is running.

Just to clarify, we only pause these during the __repositories stage__ of a backup and restore, and the __storage stage__ of a backup, not the entire backup and restore process.

Specifically, the following scripts make use of `ghe-gc-disable` and `ghe-gc-enable`:

- `ghe-backup-storage`
- `ghe-backup-repositories`
- `ghe-restore-repositories-rsync`
- `ghe-restore-repositories`

**Comment by lildude** [comment]
> Document the fact maintenance/GC operations are paused when backup-utils is running. Preferably in the FAQ: https://github.com/github/backup-utils/blob/master/docs/faq.md

:+1: I'm in the process of adding a few other items to the FAQ and will add this.

**Comment by MrChrisW** [comment]
Friendly bump 🏗
