### ISSUE TITLE
Default SSH config creates errors for missing "known_hosts"

### ISSUE THREAD

**Issue by nkadel** [github/backup-utils#454]
There is a classic problem for automatic tasks and the default ssh_config options, one that causes failures when a Github Enterprise has never had an SSH connection on port 122 done by a new user in an automatic or cron job task, because the SSH hostkey is not already stored in $HOME/.ssh/known_hosts. The simplest workaround is to simply disable the use of known_hosts. This is usually done by using these SSH command line options.

-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null  -oLogLevel=ERRO

**Comment by lildude** [comment]
> I do think that at least tossing in a commented out GHE_EXTRA_SSH_OPTS with these options would be useful, and I'd be happy to submit a pull request for it.

I think this is something better suited to the documentation, possibly as a note on https://github.com/github/backup-utils/blob/master/docs/scheduling-backups.md or an new FAQ.

**Comment by nkadel** [comment]
It's been three years, with no progress. Closing the ticket.
