### ISSUE TITLE
2.11.3 and 2.11.4 use the ghe-config command which is not available on GitHub Enterprise 2.0 and 2.1

### ISSUE THREAD

**Issue by doublemarket** [github/backup-utils#463]
[Backup Utilities v2.11.4 and earlier should support GitHub Enterprise 2.10 and earlier releases](https://github.com/github/backup-utils/blob/master/docs/requirements.md#github-enterprise-version-requirements) but 2.11.3 and 2.11.4 use the `ghe-config` command which is not available on GitHub Enterprise 2.0 and 2.1 for both [backups](https://github.com/github/backup-utils/blob/v2.11.3/share/github-backup-utils/ghe-backup-settings#L31) and [restores](https://github.com/github/backup-utils/blob/v2.11.3/share/github-backup-utils/ghe-restore-settings#L50). This breaks compatibility for GitHub Enterprise 2.0 and 2.1.

When trying to take a backup of a GitHub Enterprise 2.1 instance using Backup Utilities 2.11.4, the backup of config data fails with the following error:

```
$ ./bin/ghe-backup
Starting backup of xx.xx.xx.xx in snapshot 20190116T151849
Connect xx.xx.xx.xx:122 OK (v2.1.23)
Backing up GitHub settings ...
ionice: executing ghe-config failed: No such file or directory
Backing up SSH authorized keys ...
Backing up SSH host keys ...
Backing up MySQL database ...
Backing up Redis database ...
Backing up audit log ...
Backing up hookshot logs ...
Backing up Git repositories ...
Backing up GitHub Pages ...
Backing up asset attachments ...
Backing up storage data ...
Backing up hook deliveries ...
Backing up custom Git hooks ...
Backing up Elasticsearch indices ...
Completed backup of xx.xx.xx.xx:122 in snapshot 20190116T151849 at 15:20:00
Error: Snapshot incomplete. Some steps failed: settings.
```

Because of this, the management console password is not contained in backup data.

ref: https://github.com/github/backup-utils/pull/361 the pull request that introduced the use of `ghe-config`

**Comment by lildude** [comment]
Hmmm, this is a very very old bug that only affects completely unsupported versions of GitHub Enterprise. Fixing this to cover _all_ versions prior to 2.10 is not going to be easy, and may not be worth the efforts as the methods used to store the management console password have changed quite a few times since GitHub Enterprise 2.0.

The best solution would be to use an older version of Backup Utilities that still did backup the management password until such time as the appliance is running GitHub Enterprise 2.11.3 or continue to manually set the password and upload the license until such time as you've upgraded to 2.11.3 or later.

**Comment by doublemarket** [comment]
@lildude 

> The best solution would be to use an older version of Backup Utilities that still did backup the management password until such time as the appliance is running GitHub Enterprise 2.11.3 or continue to manually set the password and upload the license until such time as you've upgraded to 2.11.3 or later.

👍 

I think it's worth adding a caution about this bug in the [version requirements documentation](https://github.com/github/backup-utils/blob/master/docs/requirements.md#github-enterprise-version-requirements) as the following description may confuse users using 2.0 or 2.1 (though now it's rare I believe).

> Backup Utilities v2.11.4 and earlier offer support for GitHub Enterprise 2.10 and earlier releases.
