### ISSUE TITLE
Redis Backup Failure when cluster.redis-master is set

### ISSUE THREAD

**Issue by robodair** [github/backup-utils#471]
Today I upgraded our GHE to 2.16.2 and set up 2 Geo-Replication instances, with the master in a 2-head HA configuration.

In the backup immediately following the setup I see this:
```
13:50:09 Backing up SSH authorized keys ...
13:50:09 Backing up SSH host keys ...
13:50:09 Backing up MySQL database ...
13:50:15 Backing up Redis database ...
13:50:16 Permission denied (publickey).
13:50:17 Backing up audit log ...
13:50:19 Backing up hookshot logs ...
13:50:20 Backing up Git repositories ...
```

The backup then fails with:
```
13:59:28 Completed backup of master.git.example.com:122 in snapshot 20190215T135008 at 13:59:21
13:59:28 Error: Snapshot incomplete. Some steps failed: redis. 
```

I believe that I narrowed the problem down to https://github.com/github/backup-utils/blob/master/share/github-backup-utils/ghe-backup-redis#L24 where:

```
redis_host=\$(ghe-config cluster.redis-master 2>/dev/null || echo "localhost")
```
will return 'git-example-com-primary'.

On a hunch I edited `/etc/hosts` on the github master instance to include:
```
127.0.0.1       localhost git-example-com-primary
```
And the backup completes successfully.

I'm not sure if the change to the configuration value is the result of replica instances or the upgrade to 2.16.2.

I think this line should be along the lines of:
```
redis_host=\$(ghe-config cluster.`ghe-config cluster.redis-master`.ipv4 2>/dev/null || echo "localhost")
```
Or perhaps GHE should be adding the instance hostname to `/etc/hosts`

**Comment by lildude** [comment]
> Or perhaps GHE should be adding the instance hostname to `/etc/hosts`

🤔 GHE already does. Each node's hostname and IP is added to `/etc/hosts.dnsmasq` with all node communication occurring over the VPN link between the nodes.

Something else is at play here as the backup output shows an SSH connection failure:

```
13:50:09 Backing up SSH authorized keys ...
13:50:09 Backing up SSH host keys ...
13:50:09 Backing up MySQL database ...
13:50:15 Backing up Redis database ...
13:50:16 Permission denied (publickey).    <----- HERE
13:50:17 Backing up audit log ...
13:50:19 Backing up hookshot logs ...
13:50:20 Backing up Git repositories ...
```

The only SSH connection that happens when backing up Redis occurs with the initial connection to the primary node:

https://github.com/github/backup-utils/blob/87fcc944bb3af093cc4b83ae35e44739608a0ccc/share/github-backup-utils/ghe-backup-redis#L20-L21

This clearly works as all other connection attempts succeeded as those parts backed up successfully.

I suspect you may have had a transient hostname resolution issue on your local network where `master.git.example.com` temporarily resolved to a different IP address and this happened to coincide with the backing up of the Redis data.

**Comment by robodair** [comment]
Thanks for taking a look @lildude!

> I suspect you may have had a transient hostname resolution issue on your local network where `master.git.example.com` temporarily resolved to a different IP address and this happened to coincide with the backing up of the Redis data.

This is certainly not the case as the failure was reproducible every backup until I added the line to `/etc/hosts`.

> The only SSH connection that happens when backing up Redis occurs with the initial connection to the primary node:

I see another one here, which is where I think the failure is occurring due to the `cluster.redis-master` hostname not being resolved (and not being localhost): https://github.com/github/backup-utils/blob/87fcc944bb3af093cc4b83ae35e44739608a0ccc/share/github-backup-utils/ghe-backup-redis#L42 outside of the cluster vpn, does /etc/hosts.dnsmasq have any influence?

**Comment by snh** [comment]
@robodair Thank you for the additional background.

We have seen issues in the past similar to this where the appliance wasn't querying the local `dnsmasq` instance (and by extension `/etc/hosts.dnsmasq`) due to `/etc/resolvconf/resolv.conf.d/head` having been modified.

It is critical that the first nameserver in this file remains as `127.0.0.1`.

Can you confirm that `/etc/resolvconf/resolv.conf.d/head` and `/etc/resolv.conf` lists `127.0.0.1` as the first nameserver?

**Comment by lildude** [comment]
Ah yes, I missed that second `ssh`. That connection should be occurring over the VPN too as it's within the parent `ghe-ssh` I mentioned before.

> /etc/hosts.dnsmasq have any influence?

It most definitely does. We use dnsmasq for hostname resolution for the nodes. When the settings are saved, GHE ensures all node names are aliased in `/etc/hosts.dnsmasq` and then we use `/etc/resolv.conf` to ensure dnsmasq is used for this resolution with: `nameserver 127.0.0.1` as the first line and comment stating this entry is required:

```
# The 127.0.0.1 entry is *required* to be the first entry in the list here. Removing it
# or having another entry as the first entry will break GitHub Enterprise. It's also not
# supported to add options that affect the ordering here such as "options rotate".
#
nameserver 127.0.0.1
```

With that in mind, possible causes that come to mind are:

- the Redis master hostname entry in `/etc/hosts.dnsmasq` is wrong or missing
- dnsmasq isn't running on the
- the `/etc/resolv.conf` file has been modified (or configured) such that dnsmasq isn't being used

**Comment by lildude** [comment]
Oops, @snh was quicker 😄

**Comment by robodair** [comment]
Thanks for the ideas!

Here's the contents of all those files, nothing I can see looks too amiss:

```
$ cat /etc/hosts
127.0.0.1       localhost ip-[Private IP] git-example-com-primary
::1     localhost6 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
```
$ cat /etc/hosts.dnsmasq
127.0.0.1 localhost



127.0.0.1 git.example.com
127.0.0.1 gist.git.example.com
127.0.0.1 media.git.example.com
127.0.0.1 raw.git.example.com
127.0.0.1 git-example-com



127.0.0.1 git-example-com-primary git-server-6187d0fa-72cb-11e8-9c56-0611944cf70a pages-server-6187d0fa-72cb-11e8-9c56-0611944cf70a storage-server-6187d0fa-72cb-11e8-9c56-0611944cf70a


169.254.179.2 git-example-com-replica git-server-4fa7b97a-30cd-11e9-a15c-024d8a78b564 pages-server-4fa7b97a-30cd-11e9-a15c-024d8a78b564 storage-server-4fa7b97a-30cd-11e9-a15c-024d8a78b564


# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
```
$ cat /etc/resolvconf/resolv.conf.d/head
# DO NOT CHANGE THIS FILE DIRECTLY. YOUR MODIFICATIONS WILL BE OVERWRITTEN.
#
# For static IP configurations, nameservers can be specified via `ghe-setup-network'.
# For DHCP configurations, nameservers are auto-populated with values provided in the DHCP lease.
# To add custom options to this file, edit /etc/resolvconf/resolv.conf.d/head and run `sudo service resolvconf restart'.
#
# The 127.0.0.1 entry is *required* to be the first entry in the list here. Removing it
# or having another entry as the first entry will break GitHub Enterprise. It's also not
# supported to add options that affect the ordering here such as "options rotate".
#
nameserver 127.0.0.1
```
```
$ cat /etc/resolv.conf
# DO NOT CHANGE THIS FILE DIRECTLY. YOUR MODIFICATIONS WILL BE OVERWRITTEN.
#
# For static IP configurations, nameservers can be specified via `ghe-setup-network'.
# For DHCP configurations, nameservers are auto-populated with values provided in the DHCP lease.
# To add custom options to this file, edit /etc/resolvconf/resolv.conf.d/head and run `sudo service resolvconf restart'.
#
# The 127.0.0.1 entry is *required* to be the first entry in the list here. Removing it
# or having another entry as the first entry will break GitHub Enterprise. It's also not
# supported to add options that affect the ordering here such as "options rotate".
#
nameserver 127.0.0.1
nameserver [Private IP]
search [aws-region].compute.internal
options timeout:1
```

**Comment by snh** [comment]
Thanks @robodair, they do indeed look fine. We'll need to dig a bit deeper here to understand what is going on.

To maintain your privacy, could you please open a support ticket with our Enterprise Support team via their [portal](https://enterprise.githubsupport.com/hc/en-us/requests/new?github_product=cloud), referencing this issue?

**Comment by robodair** [comment]
Will do, thanks @snh

**Comment by snh** [comment]
Thanks @robodair. I'll go ahead and close this issue and we'll move our troubleshooting over to the support ticket.
