### ISSUE TITLE
How to configure # of backups based on given time ranges

### ISSUE THREAD

**Issue by vila89** [github/backup-utils#474]
👋 Is there a way to be able to configure the number of backups for given time ranges (e.g. 20 hourly backups, 7 daily backups, 3 weekly backups, N monthly backups, etc.), so that the backups can have a good coverage of different time ranges. Thank you!

**Comment by lildude** [comment]
> Is there a way to be able to configure the number of backups for given time ranges (e.g. 20 hourly backups, 7 daily backups, 3 weekly backups, N monthly backups, etc.), so that the backups can have a good coverage of different time ranges.

Yup, see my response at https://github.com/github/backup-utils/issues/405#issuecomment-390136612

**Comment by primetheus** [comment]
Linking back to the original request [here](https://github.com/githubcustomers/Stripe/issues/1)

**Comment by primetheus** [comment]
thanks @lildude!

**Comment by vila89** [comment]
👍 Thank you @lildude! Very helpful!!

**Comment by shcorbett** [comment]
Looks like this has been answered - closing this out. Thanks!
