### ISSUE TITLE
ghe-export-settings sets json file extension, should be ini?

### ISSUE THREAD

**Issue by stoe** [github/backup-utils#482]
When executing `ghe-export-settings > dump-file` the resulting file is in `.ini` format, not `.json`.

Should this be addressed here?

**Occurrences**
https://github.com/github/backup-utils/blob/43406efe02eb46af69e459a51a773680f084fed9/share/github-backup-utils/ghe-backup-settings#L23

https://github.com/github/backup-utils/blob/43406efe02eb46af69e459a51a773680f084fed9/share/github-backup-utils/ghe-restore-settings#L33-L35

https://github.com/github/backup-utils/blob/43406efe02eb46af69e459a51a773680f084fed9/test/testlib.sh#L306

https://github.com/github/backup-utils/blob/43406efe02eb46af69e459a51a773680f084fed9/test/testlib.sh#L361

https://github.com/github/backup-utils/blob/43406efe02eb46af69e459a51a773680f084fed9/docs/backup-snapshot-file-structure.md#L37

**Comment by 236084298** [comment]
.dockerignore
