### ISSUE TITLE
About ghe-restore by Docker

### ISSUE THREAD

**Issue by yiwu1** [github/backup-utils#484]
Team, if we choose Docker solution, how to restore it ? I didn't find out any document introducing ghe-restore by Docker solution. Thanks in advance!

**Comment by djdefi** [comment]
The most straightforward thing to do is to simply use the same arguments / environment variables as with the `ghe-backup` command. The most important thing is to mount the data volume or container when you run the restore.

For example, if you ran the backup with options such as:

 ```
docker run -it -e "GHE_HOSTNAME=hostname" \
-e "GHE_DATA_DIR=/data" \
-e "GHE_EXTRA_SSH_OPTS=-i /ghe-ssh/id_rsa -o UserKnownHostsFile=/ghe-ssh/known_hosts" \
-e "GHE_NUM_SNAPSHOTS=15" \
-v "ghe-backup-data:/data" \
-v "$HOME/.ssh/known_hosts:/ghe-ssh/known_hosts" \
-v "$HOME/.ssh/id_rsa:/ghe-ssh/id_rsa" \
--rm \
github/backup-utils ghe-backup
```

You can run `ghe-restore` with the same flags, just changing to the restore command:

```
docker run -it -e "GHE_HOSTNAME=hostname" \
-e "GHE_DATA_DIR=/data" \
-e "GHE_EXTRA_SSH_OPTS=-i /ghe-ssh/id_rsa -o UserKnownHostsFile=/ghe-ssh/known_hosts" \
-v "ghe-backup-data:/data" \
-v "$HOME/.ssh/known_hosts:/ghe-ssh/known_hosts" \
-v "$HOME/.ssh/id_rsa:/ghe-ssh/id_rsa" \
--rm \
github/backup-utils ghe-restore <target IP>
```

If you run into any issues, feel free to reach out to support so we can debug your specific case in detail!
