### ISSUE TITLE
stderr output during backup

### ISSUE THREAD

**Issue by maennlse** [github/backup-utils#496]
Hi,
we trigger updates using cron (which iirc is the recommended way...)
since the update to 2.17.0 we get messages printed on stderr.
stdout is redirected to a logfile

```
/opt/github-backup-utils-v2.17.0/bin/ghe-backup > backup.log
2019/06/04 07:00:00 Counting from 2019-03 to 2019-05...
2019/06/04 07:00:00 2019-03
2019/06/04 07:00:00 2019-04
```

the output is generated by `/opt/github-backup-utils-v2.17.0/share/github-backup-utils//ghe-backup-mysql-audit-log` on line 44
```
44   if ! meta=$(ghe-ssh "$host" "sudo ghe-export-audit-logs months" | grep -v NULL 2>&3); then
```
and can also be reproduced on the github appliance
```
admin@github-test:~$ sudo ghe-export-audit-logs months
2019/06/04 08:28:53 Counting from 2019-03 to 2019-05...
2019/06/04 08:28:53 2019-03
2019/06/04 08:28:53 2019-04
2019-03 10 2 11
2019-04 194 12 205
2019-05 538 1 743

admin@github-test:~$ sudo ghe-export-audit-logs months >/dev/null
2019/06/04 08:29:00 Counting from 2019-03 to 2019-05...
2019/06/04 08:29:00 2019-03
2019/06/04 08:29:00 2019-04

admin@github-test:~$ sudo ghe-export-audit-logs months 2>/dev/null
2019-03 10 2 11
2019-04 194 12 205
2019-05 538 1 743
```
so this is probably a server issue with the output of `ghe-export-audit-logs months`

i don't know if this only affects our instance, but for the moment i "work around" by redirecting stderr of this single command of to /dev/null
```
44   if ! meta=$(ghe-ssh "$host" "sudo ghe-export-audit-logs months 2>/dev/null" | grep -v NULL 2>&3); then
```

not the coolest option, but at least i don't get messages every time a backup is created.

**Comment by lildude** [comment]
This is now fixed in v2.17.1. Thanks for the bug report.
