### ISSUE TITLE
GHE-Backup Fails on Audit Logs

### ISSUE THREAD

**Issue by bhaberle** [github/backup-utils#503]
After upgrading to GHE 2.17.1 I get the following message when running backup utils 2.17.1:

"Completed backup of X in snapshot X at X"
"Error: Snapshot incomplete.  Some steps failed: audit-log."

Prior to upgrading GHE to 2.17.1 I was using GHE 2.16.x with backup utils 2.17.1 and it was working fine.  I've confirmed on my end that I have plenty of space available.  I did a backup right before upgrading to GHE 2.17.1 with success.

**Comment by lildude** [comment]
@bhaberle We'll need to gather more information from one of these failed backups, however that information may contain sensitive data making this an inappropriate place to discuss and investigate further.

Please open a support ticket via the [Enterprise Support portal](https://enterprise.githubsupport.com/hc/en-us/requests/new?github_product=cloud) and provide the verbose output from one of these failing backups so my colleagues can investigate further.

As this is not the best place for investigating this issue, I'm going to close this issue.
