### ISSUE TITLE
Warning is reported on restoration pages is disabled on the appliance

### ISSUE THREAD

**Issue by robodair** [github/backup-utils#521]
There is no warning reported when backing up an appliance where pages is disabled, however when restoring this backup to a staging instance the following warning is reported:

```
Restoring GitHub Pages ...
Warning: Pages backup missing. Skipping ...
```

Is it possible for us to not report this as a warning if it is know that pages is disabled?

**Comment by davidjarzebowski** [comment]
@robodair : As described in [this issue](https://github.com/github/backup-utils/issues/1140), we are making changes to the backup-utils repository today.

I have moved this issue into our internal repository so we can work on this bug fix in the future.
