### ISSUE TITLE
Problem with the backup

### ISSUE THREAD

**Issue by alms1** [github/backup-utils#522]
When I try to make a backup, It get this error:
 
Backing up storage data ...
ls: cannot access '/tmp/backup-utils-backup-fjbo7i/*.rsync': No such file or directory
Warning: no routes found, skipping storage backup ...

What its?

Thanks

**Comment by lildude** [comment]
That warning can happen if your instance is very new without any avatars, Git LFS files, issue attachments or releases.

**Comment by alms1** [comment]
Thanks lildude! When adding data to the repository, the "error" has been fixed.
