### ISSUE TITLE
add time in output

### ISSUE THREAD

**Issue by ChristophHoyer** [github/backup-utils#529]
it might be useful to see, how long a restore takes.
Therefore it would be helpful, if the ghe-restore command could print out a timestamp at the beginning and the end of the run.
Something like:

Checking for leaked keys in the backup snapshot that is being restored ...
* No leaked keys found
Connect github.superserver.com:122 OK (v2.18.7)

WARNING: All data on GitHub Enterprise appliance github.superserver.com (v2.18.7)
         will be overwritten with data from snapshot 20191203T011002.
Please verify that this is the correct restore host before continuing.
Type 'yes' to continue: yes

Starting restore of github.superserver.com:122 with backup-utils v2.18.0 from snapshot 20191203T011002
**Start time: 2019-12-03 11:30**
Stopping cron and github-timerd ...
Restoring UUID ...
Restoring MySQL database ...
Restoring Redis database ...
Restoring Git repositories ...
Restoring Gists ...
Warning: Gist backup missing. Skipping ...
Restoring GitHub Pages ...
Restoring SSH authorized keys ...
Restoring storage data ...
Restoring custom Git hooks ...
Restoring Elasticsearch indices ...
Restoring Audit logs ...
Restoring hookshot logs ...
Configuring appliance ...
Starting cron ...
Restoring SSH host keys ...
**End time: 2019-12-03 12:00
Runtime: 00:30h**
Restore of github.superserver.com:122 from snapshot 20191203T011002 finished.

**Comment by bltstillwater** [comment]
Yes

**Comment by cainejette** [comment]
@ChristophHoyer that's a great idea! I'm not sure we have bandwidth right now to add this, but we would happily review a PR if you submitted one!

**Comment by djdefi** [comment]
It looks like this was implemented in https://github.com/github/backup-utils/pull/625
