### ISSUE TITLE
Backups can fail due to "grep: write error: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by maclarel** [github/backup-utils#560]
**Issue:**

Backups can intermittently fail due to `grep: write error: Resource temporarily unavailable`. This appears to be linked to a significant (hundreds of thousands or more) Pages objects in an environment causing the `grep` process used in conjunction with output redirection to run out of resources and fail.

**Workarounds:**

[Remove the `egrep`s from `ghe-rsync`](https://github.com/github/backup-utils/blob/master/share/github-backup-utils/ghe-rsync#L28-L30)

**Potential fix:**

In combination with potential changes to output filtering (removal of `egrep`s), investigate additional logic to backup Pages in a similar fashion to repository networks to lower the number of files being transferred.

**Comment by shcorbett** [comment]
It looks like [this PR](https://github.com/github/backup-utils/pull/881) may have resolved this but confirming if this can be closed?

**Comment by shcorbett** [comment]
Will go ahead and close this out - please reopen if issue still exists and not covered with PR above. Thanks.
