### ISSUE TITLE
2.19.5 is getting "This port is reserved for git operations." error

### ISSUE THREAD

**Issue by MarkHallEJ** [github/backup-utils#621]
Using: 
github/backup-utils 2.19.5
GitHub Enterprise: 2.19.11

I ran ghe-backup as bash-x ghe-backup and was able to isolate where this is being generated.

Here's a couple lines on either side:

`+ rm -rf src dest1 dest2}}`
`+ should_use_gitbackups_for_repositories`
`+ ghe-ssh github.{domain}.com ghe-config --true app.github.gitbackups`
This port is reserved for git operations.
To administer the host over SSH, use port 122 with `ssh -p 122`.
`+ trap cleanup EXIT`
`+ trap 'exit $?' INT`
`+ '[' -h ../in-progress ']'`
`+ '[' -f ../in-progress ']'`
...
and the backup continues as expected and completes successfully with no other errors of this nature, just for this one step.

**Comment by MarkHallEJ** [comment]
Previous releases allowed for the hostname in backup.config to be defined as just a hostname.  I was able to trace back to the backup.config definition being used to parse the port number, so I added :122 after the hostname. It did resolve the error, but for backwards compatibility, shouldn't this port number be the default even if 'unspecified'?

**Comment by ikara5** [comment]
> Using: 
> 
> github/backup-utils 2.19.5
> 
> GitHub Enterprise: 2.19.11
> 
> 
> 
> 
> 
> I ran ghe-backup as bash-x ghe-backup and was able to isolate where this is being generated.
> 
> 
> 
> Here's a couple lines on either side:
> 
> 
> 
> `+ rm -rf src dest1 dest2}}`
> 
> `+ should_use_gitbackups_for_repositories`
> 
> `+ ghe-ssh github.{domain}.com ghe-config --true app.github.gitbackups`
> 
> This port is reserved for git operations.
> 
> To administer the host over SSH, use port 122 with `ssh -p 122`.
> 
> `+ trap cleanup EXIT`
> 
> `+ trap 'exit $?' INT`
> 
> `+ '[' -h ../in-progress ']'`
> 
> `+ '[' -f ../in-progress ']'`
> 
> ...
> 
> and the backup continues as expected and completes successfully with no other errors of this nature, just for this one step.
> 
> 
> 
>

**Comment by geeebse** [comment]
#515

**Comment by geeebse** [comment]
[](https://github.com/github/backup-utils/issues/621)

**Comment by MarkHallEJ** [comment]
@geeebse we already had a working backup for 2.13. I used the same configuration file and commented about the changes I made above. However, I’m still getting that “This port is reserved...” message fro the title and my original post on every run as standard error. This error is causing issues with our autosys system And triggering someone to look at every run (hourly) because stderr has content. The information on issue 515 does not address the issue I raised, or I wouldn’t have raised it. I did check open tickets before submitting one.

**Comment by djdefi** [comment]
Going to close this as stale as GitHub Enterprise Server 3.0 is now the oldest supported version, so this has likely changed a lot since then.

If you run in to similar issues, please feel free to reach out to GitHub Enterprise Support: https://github.com/github/backup-utils#support
