### ISSUE TITLE
Ability to restore only Audit Logs

### ISSUE THREAD

**Issue by maclarel** [github/backup-utils#623]
As introduced in https://github.com/github/backup-utils/pull/596, we can now *skip* the restore of Audit logs, however there is no discrete option to *only* restore the Audit logs.

For larger environments, an incremental restore can have significant value in decreasing time before the environment is available. While avoiding the restore of Audit logs undeniably helps, it would be hugely beneficial to also be able to restore these with a discrete command *separately* from the full restore.

While there are alternatives to this such as manually copying the indices from the backup, this can be highly error prone and is not immediately obvious nor is it trivial to automate.

**Comment by cainejette** [comment]
triage: never

follow up with @itillis for more info if needed
