### ISSUE TITLE
separation of repos and alabamic storage

### ISSUE THREAD

**Issue by AxelFritz** [github/backup-utils#666]
Hello,
due to large growing of our github-enterprise server we requested to seperate repos from alabamic storage which was provided:
So we had separated disks.
for example _df -h
Filesystem                                                                        Size  Used Avail Use% Mounted on
/dev/sda2                                                                         98G   57G   37G  62% /
/dev/mapper/ghe_storage_xxxx-ghe_user_data               4.0T  2.7T  1.2T  71% /data/user
/dev/mapper/ghe_alambic_data_xxxx-ghe_alambic_data_data  4.0T  1.7T  2.1T  45% /data/alambic-data_

It would be perfect to have also the backup can be configured for separate disks or dedicate restore

**Comment by arhasan617** [comment]
> Hello,
> due to large growing of our github-enterprise server we requested to seperate repos from alabamic storage which was provided:
> So we had separated disks.
> for example _df -h Filesystem Size Used Avail Use% Mounted on /dev/sda2 98G 57G 37G 62% / /dev/mapper/ghe_storage_xxxx-ghe_user_data 4.0T 2.7T 1.2T 71% /data/user /dev/mapper/ghe_alambic_data_xxxx-ghe_alambic_data_data 4.0T 1.7T 2.1T 45% /data/alambic-data_
> 
> It would be perfect to have also the backup can be configured for separate disks or dedicate restore

Ade

**Comment by Cristiano1226** [comment]
> Olá,
> devido ao grande crescimento de nosso servidor github corporativo, solicitamos separar os repos do armazenamento alabâmico que foi fornecido:
> Portanto, tínhamos discos separados.
> por exemplo _df -h Tamanho do sistema de arquivos usado Uso disponível% Montado em / dev / sda2 98G 57G 37G 62% / / dev / mapper / ghe_storage_xxxx-ghe_user_data 4.0T 2.7T 1.2T 71% / data / user / dev / mapper / ghe_alambic_data_xxxx- ghe_alambic_data_data 4.0T 1.7T 2.1T 45% / data / alambic-data_
> 
> Seria perfeito ter também o backup pode ser configurado para discos separados ou restauração dedicada

**Comment by djdefi** [comment]
Separate `/data/alambic-data` disk is a very uncommon and undocumented setup (we no longer recommend this). As such I don't think this would be something added to backup-utils.
