### ISSUE TITLE
Can i use parallel feature?

### ISSUE THREAD

**Issue by zino7825** [github/backup-utils#667]
Our GHE is one virtual machine(stand alone) and one backup server but data size is big.

Backup job takes a lot of time.

So I want to enable parallel in backup utils.

Is the parallel feature for the cluster environment only?

**Comment by djdefi** [comment]
Hi @zino7825 -- The parallel feature can be used on Standalone and HA environments, as well as cluster.

If you run into any issues with it, feel free to reach out to support!
