### ISSUE TITLE
test-ghe-host-check.sh does not handle major version release

### ISSUE THREAD

**Issue by DangMH** [github/backup-utils#675]
Currently the logic merely subtracts 3 from the minor version to calculate an unsupported version.

Because we are releasing 3.0.0.rc1, it generates 2.-3.0, which is an invalid version.

Logic should be more robust to handle this case.

**Comment by rflett** [comment]
I'm seeing the same thing running GHES 3.0.0.rc1 and using backup-utils v3.0.0.rc1. The logs are displaying:
```
Starting backup of x.x.x.x with backup-utils v3.0.0.rc1 in snapshot 20210118T230001
backup-utils 3.0.0 or greater is required!
```

**Comment by Bellybutn278** [comment]
> Currently the logic merely subtracts 3 from the minor version to calculate an unsupported version.
> 
> Because we are releasing 3.0.0.rc1, it generates 2.-3.0, which is an invalid version.
> 
> Logic should be more robust to handle this case.

**Comment by hayya33** [comment]
Redme]()

**Comment by alejndr0** [comment]
Hi @DangMH, can you confirm if this issue was fixed by you on this PR? https://github.com/github/backup-utils/pull/674 😄 
Thank you!

**Comment by shcorbett** [comment]
Going to close this out as it looks like this may be fixed with PR referenced above ⬆️ . Please reopen if this is still an issue. Thanks!
