### ISSUE TITLE
test-ghe-restore.sh failures on master

### ISSUE THREAD

**Issue by DangMH** [github/backup-utils#677]
Currently `master` is failing the following tests:

```
test: ghe-restore cluster with matching node versions ... ...                   FAILED (12s)
test: ghe-restore missing directories or files from source snapshot displays warning ... ... FAILED (12s)
```

### test failure examples
- Release Candidate: https://github.com/github/backup-utils/runs/1704374287?check_suite_focus=true
- master: https://github.com/github/backup-utils/runs/1704388789?check_suite_focus=true

**Comment by shcorbett** [comment]
@DangMH sorry for the late response on this -- is this still failing or causing issues?
