### ISSUE TITLE
Automatically apply new updates

### ISSUE THREAD

**Issue by sushilbh** [github/backup-utils#713]
Is there a way to automatically apply the update to our Linux server? Every time a new version of "Backup-utils" available for us to download, I wanted to get that update installed on our Linux server.

Thank You,
Sushil

**Comment by rflett** [comment]
You could set up a cron to check for new releases using the [REST API](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) and then install it if there's a new one.

**Comment by sushilbh** [comment]
@rflett, thank you. Do you have a code sample (Shell) for me to check new releases?

This is something new to me and I tried tweaking the below code but doesn't seem to work. Maybe I am doing something wrong. Thank you again for your help.

curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/backup-utils/releases/latest

**Comment by rflett** [comment]
This is a pretty hacked together script that should get you going in the right direction. You will need [jq](https://stedolan.github.io/jq/) installed.

```bash
#!/bin/bash
UTIL_INSTALL_PATH="/opt/github-backup-utils"
RELEASE_INFO=$(curl -sH "Accept: application/vnd.github.v3+json" https://api.github.com/repos/github/backup-utils/releases/latest)

LATEST_RELEASE=$(echo "$RELEASE_INFO" | jq -r .tag_name | cut -c2-)
INSTALLED_RELEASE=$(cat "$UTIL_INSTALL_PATH/share/github-backup-utils/version")

if [[ "$INSTALLED_RELEASE" != "$LATEST_RELEASE" ]]; then
    # download and install the desired asset from github using $LATEST_RELEASE version
fi
```

If you just put `https://api.github.com/repos/github/backup-utils/releases/latest` into your browser you will see the output from the API call.

**Comment by sushilbh** [comment]
@rflett, thank you.
