### ISSUE TITLE
Doing a restore including settings on a clean instance imports repositories to default previous location

### ISSUE THREAD

**Issue by Xeago** [github/backup-utils#72]
```text
Restoring settings ...
Restoring Git repositories ...
rsync: [sender] write error: Broken pipe (32)
rsync: write failed on "/data/repositories/…/….pack": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(322) [receiver=3.0.8]
rsync error: error in rsync protocol data stream (code 12) at io.c(837) [sender=
3.1.0]
```

```text
% grep -A 2 device < settings.json
"storage_mode": "device",
"admin_password": null,
--
"device": {
  "path": "/dev/sdb"
},
```

We're restoring onto a instance that has received minimal manual configuration. Our hopes were that the settings were imported and take immediate effect. Right now we have to import settings, and then restore.

**Comment by Xeago** [comment]
I'm closing this since 2.0 behaves drastically different than 11.3xx which this was based on.

**Comment by rtomayko** [comment]
@Xeago Great, thanks for closing. I've been meaning to wrap around here and ask if this was still relevant.

**Comment by Xeago** [comment]
GHE2 is too different. I did not have the ability to try it on a vmware based setup which would be more similar to where we initially noticed this. I can confirm it does not occur on the AWS setup, however I don't know how different this is from the vmware based setup.
