### ISSUE TITLE
Fix release script to account for release candidates in Debian packaging

### ISSUE THREAD

**Issue by zachary-mark** [github/backup-utils#731]
In #726, @henrich reported that the recent publishing of the 3.1.0.rc1 backup-utils package generated a Debian changelog with an inappropriate version number that appeared to be newer than `3.1.0` would via `dpkg --compare-versions`.  The release publishing scripts should take this into account and generate a version number with a `~` to separate the actual version number from the qualifier to allow for the correct sort order per the [Debian Policy Manual](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version).

**Comment by ThatMother1** [comment]
Is that what you think? You separate the original version? Ummm... no! Jzt is MY sisters son, MY Stcat & Braybug are MFKN MINE BITCH. Only other person I trust is my mother. How dare YOU. And you guys up there with her.

**Comment by Dejzi31** [comment]
#131

**Comment by Dejzi31** [comment]
> #131

**Comment by davidjarzebowski** [comment]
As described in [this issue](https://github.com/github/backup-utils/issues/1140), we are making changes to the backup-utils repository today.

I have moved this issue into our internal repository so we can consider working on this issue in the future.
