### ISSUE TITLE
Duplicate Index on restore

### ISSUE THREAD

**Issue by kyle-jones** [github/backup-utils#736]
using 3.0.0 to restore from 2.22.13 the indexes have duplicates. This is the work around provided.

ghe-console -y indices=["code-search-1","commits-1","discussions-1","gists-1","issues-1","labels-1","marketplace-listings-1","projects-1","pull-requests-1","registry-packages-1","repository-actions-1","repos-1","rms-packages-1","showcases-1","team-discussions-1","topics-1","users-1","vulnerabilities-1","wikis-1"] for i in indices Elastomer::SearchIndexManager.delete_index(name: i, force: true) end exit

display output

curl localhost:9201/_cat/shards?v
curl localhost:9201/_cat/indices?v

**Comment by shcorbett** [comment]
Assuming this issue has been resolved now that we are past 2.x version -- closing out issue
