### ISSUE TITLE
Incremental Backups

### ISSUE THREAD

**Issue by jschanfung** [github/backup-utils#739]
As far as I know you always get full snapshot each time you run a backup. 

In a scenario you got large user/repo base and the volume is high e.g. > 1TB, this can start becoming slow. Is there a way to run incremental backups? 

Maybe I am asking for a few pointers on potential improvements as well.

cc: @Link-

**Comment by mzzmjd** [comment]
From a fellow GitHub Enterprise System Administrator viewpoint:

You do get a full snapshot but the backups are looking for changes to the previous snapshot to create that full backup. 

How often do you run the backup? - Running it twice a day (12 hour intervals) can help.

Also once the snapshot has been created, the backup software then removes out of date / expire snapshots. Deleting those can take some time for large instances. So the backup has completed as such, but it is the tidy up afterwards that can take time.
 
How many snapshots do you keep?

So you may also have to take into account:
What is the access speed of the disk where the backups are being run?
What is the network speed like between Primary and the backup server?

**Comment by kaldrako1** [comment]
yes ise aftermarket profit shares to reinvedtbin crypto cutrendues with high drop off markets shares

**Comment by jschanfung** [comment]
> You do get a full snapshot but the backups are looking for changes to the previous snapshot to create that full backup.
> 
> How often do you run the backup? - Running it twice a day (12 hour intervals) can help.

Do you mean running more frequently helps speed up each backup?

The context is, one customer of mine has setup DR for production GHES in a separate data centre. This backup-util is being used to achieve their RTO/RPO, which is aggressive.

> How many snapshots do you keep?
> 
> So you may also have to take into account:
> What is the access speed of the disk where the backups are being run?
> What is the network speed like between Primary and the backup server?

Those are valid questions. Will get to dig in that part too.

**Comment by mzzmjd** [comment]
> Do you mean running more frequently helps speed up each backup?

Yes. That was the recommendation from support. If you are running the backup twice a day, then it sort of means it is doing half the work. This is not actually the case, particularly if the backup is running during the working day. However, it does mean is that your overnight backup might have less work to do so that will be quicker.

**Comment by jschanfung** [comment]
> Also once the snapshot has been created, the backup software then removes out of date / expired snapshots. Deleting those can take some time for large instances. So the backup has completed as such, but it is the tidy up afterwards that can take time

> How many snapshots do you keep?

I am trying to understand further on this part. 
- Is tidy-up a step of a backup job i.e. The `ghe-backup` command?
- Looking at the [snapshot file structure](https://github.com/github/backup-utils/blob/master/docs/backup-snapshot-file-structure.md). Do we expect the tidy-up to be faster if we keep more snapshots?

**Comment by mzzmjd** [comment]
> Is tidy-up a step of a backup job i.e. The ghe-backup command?

Yes it is. It is the last stage of the backup and can take quite some time depending on the size of your instance. The backup of data will already have completed. You can see how long this part takes if you manually try to remove an out of date snapshot directory on the backup server. 

I think that the ```benchmarks``` file gives you details of the time taken for each step.

> Looking at the snapshot file structure. Do we expect the tidy-up to be faster if we keep more snapshots? Any indicative ratio/figure would be helpful

Personally, we have noticed no difference.

**Comment by sonialey25** [comment]
hackers

**Comment by ThatMother1** [comment]
> From a fellow GitHub Enterprise System Administrator viewpoint:
> 
> You do get a full snapshot but the backups are looking for changes to the previous snapshot to create that full backup.
> 
> How often do you run the backup? - Running it twice a day (12 hour intervals) can help.
> 
> Also once the snapshot has been created, the backup software then removes out of date / expired snapshots. Deleting those can take some time for large instances. So the backup has completed as such, but it is the tidy up afterwards that can take time.
> 
> How many snapshots do you keep?
> 
> So you may also have to take into account:
> What is the access speed of the disk where the backups are being run?
> What is the network speed like between Primary and the backup server?

So then you STOP MAKING SCENARIOS! Especially when you Dont own this!

**Comment by jschanfung** [comment]
Closing as not questions regarding this for now
