### ISSUE TITLE
/var/log/ logs missing in ghe-backup

### ISSUE THREAD

**Issue by MmAtBosch** [github/backup-utils#761]
Today i had to check older log files of our GHE instance and have noticed that no /var/log/ log file is part of the ghe backup. Or at least i was not able to find it in the data structure.

Didn´t find somethin correlated in here:
https://github.com/github/backup-utils/blob/master/docs/backup-snapshot-file-structure.md

At least i would expect that /var/log/github and /var/log/babeld folders are part of the backup, better the whole /var/log folder.

Can someone help me on this?

Thanks in advance!

**Comment by jianghao0718** [comment]
Hi @ManuelMinkAtBOSCH - `backup-utils` does not backup logs like `/var/logs`, to keep longer term logs, you could configure [log forwarding](https://docs.github.com/en/enterprise-server@3.1/admin/user-management/monitoring-activity-in-your-enterprise/log-forwarding)

**Comment by ManuelMinkAtBOSCH** [comment]
oh ok :/
from a system operaters pov i find it quite important to also have logs in the backup, even when they are are forwarded, as the backup maybe has other retention policies regarding storage or time than a log analayser.
I would appreaciate a configuration switch or at least a comment, that they are not part of the default backup.

**Comment by rflett** [comment]
I'm executing the `backup-utils` in a cron job and outputting logs to `/var/log`, this may be of some help:

```bash
0 * * * * github-backup /opt/github-backup-utils/bin/ghe-backup -v 1>>/var/log/ghe-backup/backup.log 2>&1
```

**Comment by Shazcarrera96** [comment]
Yes Sir
Thank You
Okay

**Comment by Shazcarrera96** [comment]
Got it, thanks!

**Comment by shcorbett** [comment]
Closing this out as this is not a feature that is currently supported and we instead use log forwarding as a means of collecting these logs longer term.

**Comment by MmAtBosch** [comment]
thanks for the answer after two years 👌🏻
