### ISSUE TITLE
Fix: exit code status when ghe-restore try to start ghe-actions while in maintenance mode

### ISSUE THREAD

**Issue by GuyMauve** [github/backup-utils#797]
The `ghe-restore` script try to run the `ghe-actions-start` when github actions are enabled. (added in PR #769)
On the server, the call of `ghe-actions-start` cause the following output: `Maintenance mode is set. Skip starting Actions.` For unknown reasons, this results on an `exit 1` code from the `ghe-restore` script. 
This behavior is bypassed by adding the `-f` option to the `ghe-actions-start` (line 96 of the [ghe-restore script](https://github.com/github/backup-utils/blob/master/bin/ghe-restore#L96)) !

**Comment by rdelany** [comment]
Fixed with https://github.com/github/backup-utils/pull/836
