### ISSUE TITLE
do we need to configure daily and hourly backups

### ISSUE THREAD

**Issue by lchundur** [github/backup-utils#798]
we have daily and hourly backups scheduled from jenkins.
both the backups are placed in different directory structure based on their backup config's
I think we don't need daily backup snapshots as hourly backup snapshots are more effective way for restoring,
please clarify my understanding

**Comment by vlad999482** [comment]
[![Check for unallowed internal changes](https://github.com/github/docs/actions/workflows/triage-unallowed-internal-changes.yml/badge.svg?branch=%23268-active-language-display)](https://github.com/github/docs/actions/workflows/triage-unallowed-internal-changes.yml)

**Comment by vlad999482** [comment]
[![Check for unallowed internal changes](https://github.com/github/docs/actions/workflows/triage-unallowed-internal-changes.yml/badge.svg?branch=%23268-active-language-display)](https://github.com/github/docs/actions/workflows/triage-unallowed-internal-changes.yml)

**Comment by vlad999482** [comment]
[![.github/workflows/greetings.yml](https://github.com/github/docs/actions/workflows/greetings.yml/badge.svg?branch=%23268-active-language-display)](https://github.com/github/docs/actions/workflows/greetings.yml)

**Comment by shcorbett** [comment]
closing out issue as it looks like question above was answered. Please reopen if additional questions - thanks!
