### ISSUE TITLE
Configure full backup disabling incremental ones

### ISSUE THREAD

**Issue by kikuingithub** [github/backup-utils#801]
Need to configure full backup everytime the schedule runs so that we can restore easily. 
We are looking to implement a daily rotational backup for our github enterprise server, where old backups will get deleted weekly once.  
Having incremental backup puts dependency on the previous day's backup while restore ( correct me if i am wrong !).

**Comment by kikuingithub** [comment]
Team, 

Did you get a chance to look into this ?

**Comment by ChrisOwenBoring** [comment]
Would be good to understand this as well.

I'm not overly familiar with the backup-utils, and was only just starting to use them but I assumed it was governed by this block in the settings file:

`
# Cadence of MSSQL backups
# <full>,<differential>,<transactionlog> all in minutes
# e.g.
#   - Full backup every week (10080 minutes)
#   - Differential backup every day (1440 minutes)
#   - Transactionlog backup every 15 minutes
#
#GHE_MSSQL_BACKUP_CADENCE=10080,1440,15
`

Going to do some testing to see if I can get the desired behaviour.

**Comment by ChrisOwenBoring** [comment]
If you set the cadence to something like 45,0,0 and then schedule the backup hourly you seem to get the desired behaviour (full backup everytime you run a backup).


That's only based on the size of the resultant backup directory however. And I'm not sure if there is a cleaner way.

```
# Cadence of MSSQL backups
# <full>,<differential>,<transactionlog> all in minutes
# e.g.
#   - Full backup every week (10080 minutes)
#   - Differential backup every day (1440 minutes)
#   - Transactionlog backup every 15 minutes
#
GHE_MSSQL_BACKUP_CADENCE=45,0,0
```

**Comment by jianghao0718** [comment]
> Having incremental backup puts dependency on the previous day's backup while restore ( correct me if i am wrong !).

Yes, it is using hard links to previous backup so it reduces backup time and also save space on your backup server. I don't think it will significantly impact your restore time though. This applies to repository / storage / audit log backups.

MSSQL backup incremental backups is different, that might have impact of restore time, @zarenner might have better idea. Seems the suggestion from @ChrisOwenBoring makes sense if you prefer daily full backups of MSSQL.

**Comment by shcorbett** [comment]
Closing out issue as it looks like comments/answers provided. Please reopen if there are still questions or any other issues. Thanks!
