### ISSUE TITLE
s3cmd feature

### ISSUE THREAD

**Issue by nomadicj** [github/backup-utils#83]
Are you guys holding out on pushing the s3cmd functionality? Is it just a matter of getting someone to contribute to finish it off?

**Comment by davideg** [comment]
Curious if there's any more interest/movement here?

Related issue: https://github.com/github/backup-utils/issues/92

**Comment by lildude** [comment]
Closing this as adding native S3 support is not on our current roadmap and not likely to be for some time.

If and when S3 or any other object-based storage support is added, this will be clearly documented in the release notes.
