### ISSUE TITLE
stable branch on 3.2

### ISSUE THREAD

**Issue by ChristophHoyer** [github/backup-utils#835]
Hej there!
Is it intended, that the stable branch (as mentioned in the documentation) still points to the version 3.2?

Here's the documentation, which mentions this stable branch to download the "latest" version:
--> https://github.com/github/backup-utils/blob/master/docs/getting-started.md

**Comment by snh** [comment]
Thank you for bringing this to our attention @ChristophHoyer. This should be resolved now, with `stable` now pointing at the same commit as the latest tagged release - `v3.3.0`.

**Comment by ymadavar** [comment]
Hi @snh Looks like we have similar issue now for 3.10.2 release, stable is pointing to 3.10.0 backup release version. Can you please let us know when stable version will be pointed to 3.10.2 release.

**Comment by ymadavar** [comment]
Thank you @JoeFranks1993 for checking on this, I just did curl of the stable https://github.com/github/backup-utils/archive/stable.tar.gz, looks like it is pointed to 3.10.1 but not 3.10.2 latest release, is 3.10.1 is the stable or 3.10.2, please let me know.
<img width="504" alt="image" src="https://github.com/github/backup-utils/assets/94468638/c7c3414c-79d3-4626-bae6-83103bd99d2c">

**Comment by ChristophHoyer** [comment]
they just forgot to update the version file here:
https://github.com/github/backup-utils/blob/v3.10.2/share/github-backup-utils/version
That would explain the wrong output of `--version`.

**Comment by ymadavar** [comment]
but here in https://github.com/github/backup-utils/releases/download/v3.10.2/github-backup-utils-v3.10.2.tar.gz file have updated version which is what need to be pointed to stable i guess
