### ISSUE TITLE
test-ghe-restore-parallel tests broken on macOS

### ISSUE THREAD

**Issue by zarenner** [github/backup-utils#841]
https://github.com/github/backup-utils/pull/839 fixes macOS tests in general but leaves `test-ghe-restore-parallel` tests disabled for now since I wasn't able to easily fix them (and it's a "beta" feature that likely isn't used much).

As far as I can tell, the failure is due to parallel rsync invocations from `ghe-restore-storage` conflicting:
```
    /Users/zarenner/backup-utils/test/tmp/test-ghe-restore-parallel.sh-56413/out:rsync: mkdir "/Users/zarenner/backup-utils/test/tmp/test-ghe-restore-parallel.sh-56413/remote/data/user/storage" failed: File exists (17)
    /Users/zarenner/backup-utils/test/tmp/test-ghe-restore-parallel.sh-56413/out:rsync error: error in file IO (code 11) at /System/Volumes/Data/SWE/macOS/BuildRoots/38cf1d983f/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(545) [receiver=2.6.9]
    /Users/zarenner/backup-utils/test/tmp/test-ghe-restore-parallel.sh-56413/out:rsync: connection unexpectedly closed (8 bytes received so far) [sender]
    /Users/zarenner/backup-utils/test/tmp/test-ghe-restore-parallel.sh-56413/out:rsync error: error in rsync protocol data stream (code 12) at /System/Volumes/Data/SWE/macOS/BuildRoots/38cf1d983f/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/io.c(453) [sender=2.6.9]
```

There's some logic to attempt to mitigate this sort of problem, but perhaps it's not working as expected (is it supposed to have the same temp directory for every rsync invocation as it currently does?) 
https://github.com/github/backup-utils/blob/dba983945bea92867c4742f8ef29089365443423/test/test-ghe-restore-parallel.sh#L7-L11

**Comment by djdefi** [comment]
MacOS is not one of our tested or supported platforms at this time
