### ISSUE TITLE
Scripts assume /bin/sh is POSIX compliant

### ISSUE THREAD

**Issue by lildude** [github/backup-utils#85]
All the scripts in backup-utils assume the host on which they're being run has a bash-compatible `/bin/sh`.  This isn't the case on Solaris 10 and earlier where `/bin/sh` is the original Bourne shell which is not 100% compatible with bash.

To ensure better cross-platform compatibility, the scripts should explicitly use `#!/bin/bash`

**Comment by snh** [comment]
Fixed by #177
