### ISSUE TITLE
Restarting Actions after aborting

### ISSUE THREAD

**Issue by ChristophHoyer** [github/backup-utils#859]
Hej there!
When you start the ghe-restore command and "forgot" to set the target github instance into maintenance mode, then the restore aborts.
But in the next line it still restarts the actions. I guess, this is not 100% correct.

```
Please verify that this is the correct restore host before continuing.
Type 'yes' to continue: yes

Start time: 1642679863
Starting restore of X.X.X.X:122 with backup-utils v3.3.1 from snapshot 20220118T005006
Error: X.X.X.X:122 must be put in maintenance mode before restoring. Aborting.
Restarting Actions after restore ...
```

**Comment by zarenner** [comment]
fyi @ritchxu @rdelany

**Comment by ritchxu** [comment]
Restarting Actions is [part of the cleanup process](https://github.com/github/backup-utils/blob/e9f6218947db9cd6e59a6c69d3c56072afb78f8b/bin/ghe-restore#L95).

I agree technically it's only necessary after the `ghe-restore` command [successfully executed `ghe-actions-stop`](https://github.com/github/backup-utils/blob/e9f6218947db9cd6e59a6c69d3c56072afb78f8b/bin/ghe-restore#L368).
