### ISSUE TITLE
Please standardize release archive file naming

### ISSUE THREAD

**Issue by justinwyer** [github/backup-utils#871]
Currently release file naming is non standard, specifically `-v` & `_` as well as extension `gz` & `xz` are changing between versions. This is problematic for automation.

Here are the last 4 releases:
```
github-backup-utils_3.4.0.tar.xz
github-backup-utils-v3.3.1.tar.gz
github-backup-utils_3.3.0.tar.xz
github-backup-utils-v3.2.0.tar.gz
```

**Comment by donal** [comment]
@justinwyer Sorry about that! We'll be sticking with the `github-backup-utils-v3.3.1.tar.gz` from now on. I'll also go back and fix the incorrect ones (noting that the contents of both file formats are the same).

**Comment by NocJockey** [comment]
Thanks @donal 
Could we standardise default extracted directory name too?
v3.4.1 extracted to "github-backup-utils-v3.4.0-8-gece0958" rather than "github-backup-utils-v3.4.1"

**Comment by donal** [comment]
@NocJockey That's my mistake — sorry about that! I'll get that file updated too.

**Comment by donal** [comment]
> v3.4.1 extracted to "github-backup-utils-v3.4.0-8-gece0958" rather than "github-backup-utils-v3.4.1"

The correct version of the [github-backup-utils-v3.4.1.tar.gz](https://github.com/github/backup-utils/releases/download/v3.4.1/github-backup-utils-v3.4.1.tar.gz) file has now been uploaded to [the v3.4.1 release](https://github.com/github/backup-utils/releases/tag/v3.4.1) (the content is the same, but now extracting to the `github-backup-utils-v3.4.1` directory).

**Comment by donal** [comment]
All of the release assets are in the correct format — `.tar.gz` files with the correct naming format and that extract to the correctly named directly.

Closing this. If you notice any other issues with the release assets, please open a new issue, thanks.

**Comment by NocJockey** [comment]
v.3.9.0 utils re-introduced this bug, with the filename "github-backup-utils_3.9.0.tar.gz" missing the 'v' before the version number

**Comment by shcorbett** [comment]
Re-opening issue per above comments to look at 3.9

**Comment by JoeFranks1993** [comment]
Adding this to the release's team backlog

**Comment by dooleydevin** [comment]
Hey folks 👋 I corrected this issue a few weeks back, but hadn't seen this open so never closed it out. Going to close this out, feel free to open it back up or @ me in a comment if you spot any incorrect package names that I missed.
