### ISSUE TITLE
SAML mappings prevent users from logging in on restore.

### ISSUE THREAD

**Issue by cvega** [github/backup-utils#876]
When restoring from backup successfully users are encountering the following error message:

`Another user already owns the account. Please have your administrator check the authentication log.`

This can be mitigated with the following details:

```bash
gh-console -y
users = User.find_each
user.each{|u| SamlMapping.where(name_id: u.name).destroy_all}
```

GitHub Expert Services is looking to understand if something in backup-utils would be able to prevent this from occurring.

**Comment by ChristophHoyer** [comment]
good point!
I also wonder, why most settings are kept and not overwritten by the restore process - but this SAML settings are overwritten (and definitely break the environment).

**Comment by thomasjohncole** [comment]
Autodesk is experiencing this as they test migration to AWS - they have restored from backup a couple times and come across what appears to be a small subset of users which cannot log in after restore.

We previously gave them a command fix for individual users:
`echo "ActiveRecord::Base.filter_attributes = []; SamlMapping.where(name_id: 'username').destroy_all" | ghe-console -y`

It looks like @cvega has a better solution above that just resets all users. @cvega is this happening consistently after restore for you? Autodesk has restored twice that I know of and had the same problem, albeit different users, both times.

related error:

```
D, [2023-02-27T23:25:47.678685 #149] DEBUG -- : now="2023-02-27T23:25:47Z" method="GitHub::Authentication::SAML.rails_authenticate" ip=10.35.153.175 login=50ec2a2e-7c1c-4581-8975-758745b5f83d at="failure - user not found" message="Another user already owns the account. Please have your administrator check the authentication log."
```

https://github.zendesk.com/agent/tickets/2173570
https://github.zendesk.com/agent/tickets/2033680

**Comment by davidjarzebowski** [comment]
As described in [this issue](https://github.com/github/backup-utils/issues/1140), we are making changes to the backup-utils repository today.

I have moved this issue into our internal repository so we can consider working on this issue in the future.
