### ISSUE TITLE
Scripts ignoring extra SSH options

### ISSUE THREAD

**Issue by guillermoandrae** [github/backup-utils#88]
I'm migrating from GHE 11.10.348. I've been having difficulty running `ghe-restore` on my backup host because of the non-standard port being used for SSH in GHE 2. I tried setting the port using `GHE_EXTRA_SSH_OPTS`, but that didn't work at all -- I kept getting error messages that let me know the script was still trying to connect over port 22. I added an entry to my SSH config file to force it to use port 122 when connecting to the IP of the new instance, but the script was still trying to connect using port 22. I did some digging, and it looks like lines [40](https://github.com/github/backup-utils/blob/master/share/github-backup-utils/ghe-ssh#L40)-[45](https://github.com/github/backup-utils/blob/master/share/github-backup-utils/ghe-ssh#L45) of `ghe-ssh` are the reason why. I got the restore to work by running:
```
ghe-restore 10.0.0.0:122
```
Would it be possible for the script to determine the version of the GHE instance to which data is being migrated (or, even better, for the `ghe-ssh` script to figure it out) and use the appropriate port? If not that, I think users should be able to explicitly set the port in the config.

Or maybe I did something completely wrong... and if that's the case, please feel free to call me names and point out my mistake(s).

**Comment by Xeago** [comment]
I'm note quite sure why you're experiencing this. The port should be detected. See the comment at https://github.com/github/backup-utils/blob/377dab5ca616541a7b4d254c6a0ad9f472d7fd1d/share/github-backup-utils/ghe-backup-config#L177

**Comment by lildude** [comment]
@guillermoandrae It sounds like you may be using an old version of backup-utils. Please update to the latest stable version (or master as it's pretty stable too) and let us know if the problem persists.

**Comment by Xeago** [comment]
Fwiw, I'm using HEAD at the time of writing in production.

**Comment by guillermoandrae** [comment]
I'll try this out again in the AM.

**Comment by guillermoandrae** [comment]
`master` works. Sorry!
