### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by muddflappz** [github/backup-utils#89]
I am probably just being thick but I could use more detail in the documentation to explain the incremental backup structures and disaster recovery scenario.

I have not yet had to restore from backups but I am not comfortable understanding whether the initial full backup produced + the incremental rolling snapshots can just be left on autopilot (I use a Jenkins job to drive our schedule) or if I need to do periodic full backups or other maintenance; basically what gets pruned and what gets kept?

And how do I force a full backup?

The interest of course is being absolutely certain that I know we can restore our entire stream of history up to the last incremental backup.

**Comment by michaeltwofish** [comment]
@muddflappz There's no need to force a full backup, every snapshot is complete and can be used for a complete restore.

To avoid transferring and storing unchanged data, each snapshot uses hard links to reference the same data on disk. If an older snapshot is purged, that snapshot's link is removed but newer snapshots will still reference the same data on disk.

Would adding something like :point_up: to the [backup snapshot file structure](https://github.com/github/backup-utils#backup-snapshot-file-structure) section help?

**Comment by muddflappz** [comment]
I've got it now.   Understanding that it's stacking up links as time progresses clears the whole picture for me.  Thanks so much!

**Comment by muddflappz** [comment]
Yep, I was being thick.

**Comment by michaeltwofish** [comment]
No worries, glad I could clear things up :+1:
