### ISSUE TITLE
Enabling the parallel feature in production

### ISSUE THREAD

**Issue by FearlessHyena** [github/backup-utils#919]
Hello, regarding the ghe-backup parallel jobs feature, is it safe to enable it in production currently?
Or are there any known issues that we need to be careful about?

The backup config file mentions that this is still a beta feature but this seems to have been implemented almost 2 years ago in #597 so was just wondering if it was stable enough at this point

**Comment by FearlessHyena** [comment]
Any information on this would be appreciated
If it's already a stable feature then the `beta` tag should probably be removed

**Comment by Sopian1996** [comment]
> Hello, regarding the ghe-backup parallel jobs feature, is it safe to enable it in production currently? Or are there any known issues that we need to be careful about?
> 
> The backup config file mentions that this is still a beta feature but this seems to have been implemented almost 2 years ago in #597 so was just wondering if it was stable enough at this point

**Comment by djdefi** [comment]
👋🏻 I don't believe we have gotten a lot of feedback (positive or negative) on the parallel feature to really decide one way or the other as of yet.

**Comment by FearlessHyena** [comment]
Thanks for the follow up. If there hasn't been any negative feedback I think it's probably a good idea to just remove the beta tag and just track any issues as they're reported in future
It's been quite a while since it was released and there are internal tests for it I'm guessing it's fairly stable at this point

**Comment by djdefi** [comment]
cc: @github/ghes-infrastructure regarding suggestion to remove "beta" status for backup-utils parallel features

**Comment by shcorbett** [comment]
thanks @FearlessHyena @djdefi - we will take a look at this and if it makes sense remove the beta tag - adding to our backlog to look at.

**Comment by shcorbett** [comment]
PR merged to update documentation - closing this issue out. Thanks!
