### ISSUE TITLE
Backups failing while waiting on Git GC processes to finish

### ISSUE THREAD

**Issue by FearlessHyena** [github/backup-utils#921]
After upgrading to GHES 3.4 (currently 3.4.1) our backups (using backup-utils 3.4.1) are failing regularly - about 2-3 times daily at least for backups taken every 3 hours
The cause is always this

```
Backing up Git repositories ...
--
Error: Git GC processes remain after 5400 seconds. Aborting...
```

I've tried setting `GHE_GIT_COOLDOWN_PERIOD` to 5400 seconds in the `backup.config` file in hopes that increasing the timeout would fix the issue but that didn't seem to help either
Our backups used to take 20-30 minutes and the only major change was the upgrade to v3.4
Is this a known issue? And is there any way to mitigate this?

**Comment by djdefi** [comment]
Sounds like possibly a stuck maintenance job, or failed maintenance that is causing processes to hang around. I suggest reaching out to support via https://support.github.com/contact and including a support bundle of the system being backed up to check for indication of trouble on any repos.

Additionally, the max runtime for a GC job is 120 minutes, so you could also try setting the `GHE_GIT_COOLDOWN_PERIOD` to just over `7200`.

**Comment by FearlessHyena** [comment]
Thanks for the suggestions. I'll try them out

**Comment by Himo777** [comment]
https://www.g2.com/assistant/21de2a41-cc81-4968-85af-a32420a8e814?secure%5Bid%5D=21de2a41-cc81-4968-85af-a32420a8e814&secure%5Brole%5D=editor&secure%5Btoken%5D=d36e18d5fa203ad5fef8f49e9e14f0cba4879704985f4a1e4df049a72cf552bf&tab=results

**Comment by shcorbett** [comment]
Based on above recommendation - closing out this issue. Thanks!
