### ISSUE TITLE
[: =: unexpected operator

### ISSUE THREAD

**Issue by AndreasStokholm** [github/backup-utils#93]
I just set up a new Ubuntu 14.04 machine to handle backups of our GHE installation. Following the [guide](https://github.com/github/backup-utils) everything works fine, until I get to step 5.

Running the command `bin/ghe-backup` in any way I can imagine all gives the same error:

`/bin/ghe-backup: 40: [: =: unexpected operator`

I've tried exchanging the sh header to a bash header, but the error just changes to bash lingo:

`bin/ghe-backup: line 40: [: =: unary operator expected`

Any tips on what I can do from here?

**Comment by tmm1** [comment]
Could you provide the full output of the `ghe-backup` command?

**Comment by AndreasStokholm** [comment]
That is the full output.

Running it this way:

```shell
~/backup-utils$ bin/ghe-backup
bin/ghe-backup: line 40: [: =: unary operator expected
```

**Comment by tmm1** [comment]
How about `bin/ghe-backup -v`

**Comment by AndreasStokholm** [comment]
Same exact output. Looking at the code, and output, it looks like a syntax error, which I'm not sure I understand.

**Comment by tmm1** [comment]
The patch in https://github.com/github/backup-utils/commit/d2dfff65acf83a191acc948defb7e371c6b9236e should fix the syntax error you're seeing. However, I'm not sure what is causing the cleanup function to be invoked before anything else happens in your case.

**Comment by AndreasStokholm** [comment]
Nice! Thanks.

Neither am I. The only place it gets called is in the exit trap, right? That correlates well with the script giving no output since I pulled your patch. 

I'm seeing neither `echo "Starting backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP"` or `echo "Error: backup of $GHE_HOSTNAME already in progress in snapshot $snapshot. Aborting." 1>&2`. It's just blank, nothing.

**Comment by AndreasStokholm** [comment]
After some carefully placed echo statements, I've deducted that the problem is on the first line after:

 `if ! ln -sn "$GHE_SNAPSHOT_TIMESTAMP" ../in-progress 2>/dev/null; then`

Offending line:

`snapshot="$(readlink ../in-progress)"`

Not at all sure why that makes the script exit.

**Comment by tmm1** [comment]
@AndreasStokholm can you try `snapshot="$(readlink ../in-progress || true)"`

**Comment by tmm1** [comment]
Or perhaps remove the `2>/dev/null` from the `ln` line to surface any errors. I suspect there might be a permissions issue at play.

**Comment by tmm1** [comment]
Adding a `set -x` at the top of the file should help debug as well.

**Comment by AndreasStokholm** [comment]
Yup, there we have it. Permission denied. I'm unsure as to why it gives a permission error, I am in the users home directory.

**Comment by AndreasStokholm** [comment]
Just for the heck of it, I ran it with sudo, same permission problem.

**Comment by AndreasStokholm** [comment]
Okay, so I figured out what the issue is. I've mounted a smb drive and set a folder on it as the backup destination. When I changed the backup directory back to the default "data", it suddenly started working.

Guess I'm off to do some research on why symlinks break on smb drives.

**Comment by AndreasStokholm** [comment]
I ended up changing from a smb share to a nfs share. There are no symlink issues on here. Apparently smb and linux symlinks are not good friends.
