### ISSUE TITLE
GH connect restore

### ISSUE THREAD

**Issue by pranereddy** [github/backup-utils#938]
Hello There,

We have a requirement where GH connect needs to be restored even without the -c flag. Right now, commenting the block https://github.com/github/backup-utils/blob/634d313c8c64bbf1b0612734eadc25980ce43ea0/bin/ghe-restore#L519 that resets the GH connect settings would work. It would be great if there is an official way, may be a flag for GH connect settings so that the extra step of reset is avoided.
```
if ! $RESTORE_SETTINGS; then
  echo "if [ -f /usr/local/share/enterprise/ghe-reset-gh-connect ]; then /usr/local/share/enterprise/ghe-reset-gh-connect -y; fi" |
  ghe-ssh "$GHE_HOSTNAME" -- /bin/sh 1>&3
fi
```

Also, are there any plans just to backup and restore only the settings without data.

Best,
Reddy.

_2022-08-25 Update by @Maximisch : Make link point to code state as it was during creation of this issue._

**Comment by davidjarzebowski** [comment]
As described in [this issue](https://github.com/github/backup-utils/issues/1140), we are making changes to the backup-utils repository today.

I have moved this issue into our internal repository so we can consider working on this issue in the future.
