### ISSUE TITLE
ghe-restore should recreate cache directories on 11.10.3xx

### ISSUE THREAD

**Issue by lildude** [github/backup-utils#95]
Raising this on behalf of an Enterprise customer.

`ghe-restore` currently removes the `/data/repositories/__nodeload_archives__/`, `/data/repositories/__gitmon__/` and `/data/repositories/__render__/` cache directories when restoring to an 11.10.3[45]x appliance and doesn't recreate them forcing the administrator to remember to save the settings and/or perform a full configuration run after each restore or just before "going live" with the restore appliance.

In the case of continual backup & restore to another standby appliance, the settings are likely to have already been verified when the appliance was first created so the administrator is not likely to think to save them again after subsequent restores and will just disable maintenance mode.  This will result in things like Wikis, Pages and archive downloads not working.

**Comment by rtomayko** [comment]
Hmm, looks like we may just need to add something like the following for 340:

https://github.com/github/backup-utils/blob/master/bin/ghe-restore#L198-L203

I'm not entirely sure why we're doing that only on 2.0. Maybe because the config run is so long on 340?
