### ISSUE TITLE
How to check if back or restore are using parallel way

### ISSUE THREAD

**Issue by GranitFazliuRB** [github/backup-utils#969]
I have installed the required moreutils and GNU gawk, although not sure if 100% correctly so how do i check this when I'm running a backup or restore that its working in parallel now?

**Comment by chuckp22** [comment]
In addition to installing the required utils, please make sure to update `backup.config` to enable the `GHE_PARALLEL_*` configuration values as appropriate.

Based on the setup you should see multiple instances of `rsync` while backup is running...so something like
 `ps aux | grep rsync` should highlight it.

**Comment by GranitFazliuRB** [comment]
Unfortunately it seems there were some issues when i tried to install GNU gawk or moreutils, backuputils couldn't find "parallel" i installed that manually then it said can't find "moreutils" as if it is 1 runnable command like docker/npm or something. I think I'm going to give up on this, might look into the BackupUtils Docker solution instead.

**Comment by shcorbett** [comment]
@GranitFazliuRB sounds good - the docker solution is the recommended way - please reopen if you have questions once you look at that. Thanks.
