### ISSUE TITLE
Default SSH Port for Github Enterprise 2.0 is now 122

### ISSUE THREAD

**Issue by geoffr** [github/backup-utils#97]
This breaks the rsync portion of the backup, I got around this by specifying the host with ":122" at the end e.g. github.example.com:122

**Comment by guillermoandrae** [comment]
I had a [similar issue](https://github.com/github/backup-utils/issues/88). Just needed to make sure I pulled down the latest version of the utils. Once I did, things seemed to work for me without having to specify the port.

**Comment by rtomayko** [comment]
Yep, auto port detection was added in the v2.0 release. Let me know if upgraded fixes things up. Thanks!

**Comment by geoffr** [comment]
I had latest which wasn't working but then noticed I had a ssh config which specified the port for that host.  Took the entry out and it worked.  Thanks for the responses

**Comment by rtomayko** [comment]
> I had latest which wasn't working but then noticed I had a ssh config which specified the port for that host.

Ahh, that may be worth calling out in the docs at least. I'll see about adding something. Thanks for the report!
