### ISSUE TITLE
Matrix table of GitHub Enterprise Server version requirements

### ISSUE THREAD

**Issue by kyanny** [github/backup-utils#977]
[GitHub Enterprise Server version requirements](https://github.com/github/backup-utils/blob/master/docs/requirements.md#github-enterprise-server-version-requirements) is a little complicated. So, I created a [matrix table](https://github.com/kyanny/caniuse-backup-utils/blob/main/matrix.csv) to see it visually.

- https://github.com/kyanny/caniuse-backup-utils

It would be nice if we can see the matrix table as a part of [github/backup-utils](https://github.com/github/backup-utils) project.

**Comment by shcorbett** [comment]
@kyanny thank you for creating this matrix - we only support GHES releases for 1 year so currently we support 3.7, 3.5, 3.4 and 3.3 (3.3 deprecates 12/31/22). And then we would support backup-utils 2 version behind each of those releases. So we wouldn't need a matrix that goes back to 2.x. And that matrix will change each time a new release goes out. We can look to see if there is anything we can post as part of the project to make it clearer on what is supported.

**Comment by shcorbett** [comment]
Closing this out as we are tying this as part of the release process now
