### ISSUE TITLE
Backup to mounted samba share fails silently

### ISSUE THREAD

**Issue by juchiu** [github/backup-utils#98]
bin/ghe-backup Lines 53-60

``` shell
# Mark the snapshot as in-progress by creating the symlink. If this fails, it
# means another ghe-backup run is already in progress and we should exit.
# NOTE: The -n argument to ln is non-POSIX but widely supported.
if ! ln -sn "$GHE_SNAPSHOT_TIMESTAMP" ../in-progress 2>/dev/null; then
    snapshot="$(readlink ../in-progress)" ### Does not get past this point
    echo "Error: backup of $GHE_HOSTNAME already in progress in snapshot $snapshot. Aborting." 1>&2
    exit 1
fi

```

If you try to have `$GHE_DATA_DIR` as a samba mount, `ln` fails to create symlinks. 
When the line with `readlink` fails, the script exits with exit code 1 without any output.

Perhaps this is just an issue with the CIFS driver, but it is very confusing when there is no output.

**Comment by Efpophis** [comment]
This is an issue on any filesystem that doesn't support linux-style symbolic links. FWIW, it also prevents using the backup utilities in a git-bash shell on Windows, placing the backup data onto (for example) a pre-formatted USB drive, and a host of other things that could be potentially useful.
