### ISSUE TITLE
URL for Adding SSH keys is no longer available.

### ISSUE THREAD

**Issue by smarj** [github/backup-utils#980]
While doing a restore today I noticed the URL provided for adding SSH keys, `https://enterprise.github.com/help/articles/adding-an-ssh-key-for-shell-access` is no longer available. I don't see a quick replacement at this time.

This search shows the location of the two URLs in the code:

https://github.com/search?q=repo%3Agithub%2Fbackup-utils%20https%3A%2F%2Fenterprise.github.com%2Fhelp%2Farticles%2Fadding-an-ssh-key-for-shell-access&type=code

**Comment by djdefi** [comment]
https://docs.github.com/enterprise-server/admin/configuration/configuring-your-enterprise/accessing-the-administrative-shell-ssh would probably be the most appropriate top level URL to replace it with.
