### ISSUE TITLE
ghe-backup doesn't gracefully deal with failed backups

### ISSUE THREAD

**Issue by tedivm** [github/backup-utils#99]
If a backup fails before finishing, causing the script to end prematurely, then subsequent runs will continue to fail as it'll think that a backup is still in progress.

````shell
$ ./bin/ghe-backup 
Error: backup of github.local already in progress in snapshot 20150129T135627. Aborting.
````

Rather than rely on the existence of a symlink to determine whether a backup is running, using a pid file and then confirming that the pid actually has a running process associated with it would be far, far more robust than the current method 

Relevant code- https://github.com/github/backup-utils/blob/master/bin/ghe-backup#L53

**Comment by tedivm** [comment]
bump- it's pretty easy to trigger this, and it means that all backups are going to fail after this issue happens.

**Comment by rtomayko** [comment]
> bump- it's pretty easy to trigger this, and it means that all backups are going to fail after this issue happens.

Agreed. I'm trying to carve out a few days to attack a bunch of these smaller issues within the next couple weeks. Sorry for the delay thus far.

**Comment by tedivm** [comment]
Awesome, glad to hear it!

**Comment by josh-padnick** [comment]
We're running into this issue as well.  For a commercially supported backup system, it seems like this should be an important feature.  Unfortunately, due to a few stability issues we've run into w/ backup-utils we've reverted to taking daily snapshots (AMIs) of our EC2 instance.

**Comment by tedivm** [comment]
The fact that this issue still hasn't been resolved is downright pathetic. You are charging people thousands of dollars for this software and your backup solution is known to be easily breakable.

And yes, I just came across this problem again. We're backing up to an AWS Storage Gateway, and it restarted itself for maintenance while a backup was recurring. Now several days later I'm manually fixing this mess.

**Comment by tedivm** [comment]
@josh-padnick - heads up, deleting "in-progress" is only one part of this. If you fail part way through you could encounter #144, which is unfortunately a silent error. Make sure you test your backups or you might not have any.

**Comment by josh-padnick** [comment]
@tedivm Thanks for the head's up!  Honestly, we had too little confidence in the official backup method, so we just decided we could tolerate up to 24 hours of data loss and while we do run the `ghe-backup` every hour, our fallback is the AMIs we take.

I agree, GitHub needs to resolve this.  It should be treated as a serious defect.

**Comment by dbussink** [comment]
First of all sorry for the delay here. I've first investigated #144 since silent failure is always much worse than explicit failure like in this issue. Agree though that the handling of a failed last backup can be much improved. I will look at that after finding what is the problem with #144.

**Comment by dbussink** [comment]
Opened #145 to handle the case where the backup was killed abruptly (with for example a `KILL` signal), so it would run the exit handlers that would clean up the `in-progress` link.
